import {
  buildQuizAnswerTtsR2Key,
  buildQuizAnswerTtsSlowR2Key,
  getR2LastModified,
  isR2Configured,
} from "./objectStorage";
import { resolveQuizCdnOrigin, publicUrlForR2Key } from "./quizMedia";
import type { KoreanQuizItem } from "./types";
import type { AnswerTtsVariant } from "./ttsUrls";

export type { AnswerTtsVariant };

function r2KeyForVariant(quizId: string, variant: AnswerTtsVariant): string {
  return variant === "slow"
    ? buildQuizAnswerTtsSlowR2Key(quizId)
    : buildQuizAnswerTtsR2Key(quizId);
}

export function answerTtsR2KeyForItem(
  item: Pick<KoreanQuizItem, "id" | "answerTtsR2Key">,
  variant: AnswerTtsVariant,
): string {
  if (variant === "normal" && item.answerTtsR2Key?.trim()) {
    return item.answerTtsR2Key.trim();
  }
  return r2KeyForVariant(item.id, variant);
}

export function hasStoredAnswerTts(
  item: Pick<
    KoreanQuizItem,
    "answerTtsR2Key" | "answerTtsUpdatedAt" | "answerTtsSlowUpdatedAt"
  >,
  variant: AnswerTtsVariant,
): boolean {
  if (variant === "slow") return Boolean(item.answerTtsSlowUpdatedAt?.trim());
  return Boolean(item.answerTtsR2Key?.trim() || item.answerTtsUpdatedAt?.trim());
}

/** Public CDN URL for app-generated answer TTS — mirrors korean-quiz getCachedAnswerTtsUrl. */
export function getCachedAnswerTtsUrl(
  item: Pick<KoreanQuizItem, "id" | "imageUrl" | "answerTtsR2Key">,
  variant: AnswerTtsVariant = "normal",
): string | undefined {
  const origin = resolveQuizCdnOrigin(item);
  if (!origin) return undefined;
  const key = answerTtsR2KeyForItem(item, variant);
  // Normal TTS: korean-quiz uploads every approved quiz image to the same CDN bucket at
  // system/quiz-tts/{id}.mp3 — do not require DB metadata (answerTtsUpdatedAt) to expose URL.
  if (variant === "normal" && item.imageUrl?.trim()) {
    return publicUrlForR2Key(key, origin) ?? undefined;
  }
  if (!hasStoredAnswerTts(item, variant)) return undefined;
  return publicUrlForR2Key(key, origin) ?? undefined;
}

function withCacheBust(url: string, cacheKey?: string): string {
  if (!cacheKey?.trim()) return url;
  const parsed = new URL(url);
  parsed.searchParams.set("v", cacheKey.trim());
  return parsed.toString();
}

/** Cache-bust token for TTS URLs — stored timestamp or R2 LastModified after regen. */
export async function resolveAnswerTtsCacheKey(
  item: Pick<
    KoreanQuizItem,
    "id" | "answerTtsUpdatedAt" | "answerTtsSlowUpdatedAt"
  >,
  variant: AnswerTtsVariant = "normal",
): Promise<string | undefined> {
  const stored =
    variant === "slow"
      ? item.answerTtsSlowUpdatedAt?.trim()
      : item.answerTtsUpdatedAt?.trim();
  if (stored) return stored;

  if (!isR2Configured()) return undefined;
  const mod = await getR2LastModified(r2KeyForVariant(item.id, variant));
  return mod ? String(mod.getTime()) : undefined;
}

/** CDN URL for browser playback — audio is generated by korean-quiz, not kajakorean.com. */
export async function resolveAnswerTtsPlaybackUrl(
  item: KoreanQuizItem,
  variant: AnswerTtsVariant = "normal",
): Promise<string | undefined> {
  const publicUrl = getCachedAnswerTtsUrl(item, variant);
  if (!publicUrl) return undefined;
  const cacheKey = await resolveAnswerTtsCacheKey(item, variant);
  return withCacheBust(publicUrl, cacheKey);
}

export async function resolveAnswerTtsApiUrl(
  item: KoreanQuizItem,
  variant: AnswerTtsVariant = "normal",
): Promise<string | undefined> {
  return resolveAnswerTtsPlaybackUrl(item, variant);
}

export { answerTtsApiUrl } from "./ttsUrls";
