/**
 * Expression SEO wave — phrase / concept / topik / similar seeds (no new grids).
 * Merged into ALL_VOCAB_BUNDLES from bundle-catalog.ts.
 */
import type { VocabInfographicFormatId } from "./formats";

type BundlePriority = "high" | "medium" | "low";

type PhraseLine = { hangul: string; romanization: string; english: string };
type ConceptRow = {
  english: string;
  hangul: string;
  romanization: string;
  visual: string;
};
type TopikRow = {
  english: string;
  topikI: { hangul: string; romanization: string };
  topikII: { hangul: string; romanization: string };
};
type SimilarPair = {
  leftEnglish: string;
  rightEnglish: string;
  leftHangul: string;
  rightHangul: string;
  leftRom: string;
  rightRom: string;
  leftNuance: string;
  rightNuance: string;
};

type VocabBundle = {
  id: string;
  format: VocabInfographicFormatId;
  title: string;
  count: number;
  fit: string;
  priority: BundlePriority;
  tags: string[];
  preview?: string[];
  conceptRows?: ConceptRow[];
  phraseLines?: PhraseLine[];
  similarPair?: SimilarPair;
  topikRows?: TopikRow[];
};

function phrase(
  slug: string,
  title: string,
  lines: PhraseLine[],
  tags: string[],
  priority: BundlePriority = "high",
): VocabBundle {
  return {
    id: `phrase-${slug}`,
    format: "phrase_stack",
    title,
    count: lines.length,
    fit: `Polished ${lines.length}-phrase stack — spoken Korean`,
    priority,
    tags: ["phrase", "spoken", ...tags],
    phraseLines: lines,
    preview: lines.map((l) => l.english),
  };
}

function concept(
  slug: string,
  title: string,
  rows: ConceptRow[],
  tags: string[],
  priority: BundlePriority = "high",
): VocabBundle {
  return {
    id: `concept-${slug}`,
    format: "concept_rows",
    title,
    count: rows.length,
    fit: "Concept diagram panels — situation beats",
    priority,
    tags: ["concept", "grammar", ...tags],
    conceptRows: rows,
    preview: rows.map((r) => r.english),
  };
}

function topik(
  slug: string,
  title: string,
  rows: TopikRow[],
  tags: string[],
  priority: BundlePriority = "high",
): VocabBundle {
  return {
    id: `topik-${slug}`,
    format: "topik_upgrade",
    title,
    count: rows.length,
    fit: `TOPIK I→II upgrade — ${rows.length} pairs`,
    priority,
    tags: ["topik", "upgrade", ...tags],
    topikRows: rows,
    preview: rows.map((r) => r.english),
  };
}

function similar(
  slug: string,
  leftEnglish: string,
  rightEnglish: string,
  leftHangul: string,
  rightHangul: string,
  leftRom: string,
  rightRom: string,
  leftNuance: string,
  rightNuance: string,
  theme: string,
  priority: BundlePriority = "high",
): VocabBundle {
  return {
    id: `sim-${slug}`,
    format: "similar_split",
    title: `${leftEnglish} vs ${rightEnglish}`,
    count: 2,
    fit: `Near-synonyms — ${theme}: ${leftNuance} / ${rightNuance}`,
    priority,
    tags: ["similar", theme],
    similarPair: {
      leftEnglish,
      rightEnglish,
      leftHangul,
      rightHangul,
      leftRom,
      rightRom,
      leftNuance,
      rightNuance,
    },
    preview: [leftEnglish, rightEnglish],
  };
}

const L = (
  hangul: string,
  romanization: string,
  english: string,
): PhraseLine => ({ hangul, romanization, english });

const C = (
  english: string,
  hangul: string,
  romanization: string,
  visual: string,
): ConceptRow => ({ english, hangul, romanization, visual });

const T = (
  english: string,
  iH: string,
  iR: string,
  iiH: string,
  iiR: string,
): TopikRow => ({
  english,
  topikI: { hangul: iH, romanization: iR },
  topikII: { hangul: iiH, romanization: iiR },
});

export const EXPR_WAVE_PHRASE_BUNDLES: VocabBundle[] = [
  phrase("greetings-casual", "Casual greetings in Korean", [
    L("안녕", "annyeong", "Hi (casual)"),
    L("잘 지냈어?", "jal jinaesseo?", "How have you been?"),
    L("오랜만이야", "oraenmaniya", "Long time no see"),
    L("뭐 해?", "mwo hae?", "What are you doing?"),
    L("나중에 봐", "najunge bwa", "See you later"),
    L("잘 가", "jal ga", "Bye (to someone leaving)"),
    L("내일 봐", "naeil bwa", "See you tomorrow"),
    L("연락할게", "yeollakhalge", "I'll text you"),
  ], ["greetings", "beginner"]),
  phrase("greetings-polite", "Polite greetings in Korean", [
    L("안녕하세요", "annyeonghaseyo", "Hello"),
    L("처음 뵙겠습니다", "cheoeum boepgetseumnida", "Nice to meet you"),
    L("잘 지내셨어요?", "jal jinaesyeosseoyo?", "How have you been?"),
    L("반갑습니다", "bangapseumnida", "Nice to meet you"),
    L("수고하세요", "sugohaseyo", "Keep up the good work"),
    L("다음에 봐요", "daeume bwayo", "See you next time"),
    L("조심히 가세요", "josimhi gaseyo", "Go carefully"),
    L("좋은 하루 보내세요", "joeun haru bonaeseyo", "Have a nice day"),
  ], ["greetings", "polite", "beginner"]),
  phrase("thanks-sorry", "Thanks & sorry phrases in Korean", [
    L("고마워", "gomawo", "Thanks (casual)"),
    L("감사해요", "gamsahaeyo", "Thank you"),
    L("정말 고마워요", "jeongmal gomawoyo", "Thank you so much"),
    L("미안해", "mianhae", "Sorry (casual)"),
    L("죄송해요", "joesonghaeyo", "I'm sorry"),
    L("실례합니다", "sillyehamnida", "Excuse me"),
    L("괜찮아요", "gwaenchanayo", "It's okay"),
    L("신경 쓰지 마세요", "singyeong sseuji maseyo", "Don't worry about it"),
  ], ["polite", "beginner"]),
  phrase("restaurant-orders", "Restaurant order phrases in Korean", [
    L("메뉴 주세요", "menyu juseyo", "Menu, please"),
    L("이거 주세요", "igeo juseyo", "I'll have this"),
    L("물 좀 주세요", "mul jom juseyo", "Water, please"),
    L("계산해 주세요", "gyesanhae juseyo", "Check, please"),
    L("따로따로 주세요", "ttarottaro juseyo", "Separate checks"),
    L("포장해 주세요", "pojanghae juseyo", "To go, please"),
    L("맛있어요", "masisseoyo", "It's delicious"),
    L("배불러요", "baebulleoyo", "I'm full"),
  ], ["food", "restaurant", "beginner"]),
  phrase("shopping-phrases", "Everyday shopping phrases in Korean", [
    L("이거 얼마예요?", "igeo eolmayeyo?", "How much is this?"),
    L("할인해요?", "harinhaeyo?", "Is it on sale?"),
    L("다른 색깔 있어요?", "dareun saekkkal isseoyo?", "Do you have another color?"),
    L("한번 입어봐도 돼요?", "hanbeon ibeobwado dwaeyo?", "Can I try it on?"),
    L("좀 더 작은 사이즈요", "jom deo jageun saijeuyo", "A smaller size, please"),
    L("이거 살게요", "igeo salgeyo", "I'll take this"),
    L("카드로 결제할게요", "kadeuro gyeoljehalgeyo", "I'll pay by card"),
    L("영수증 주세요", "yeongsujeung juseyo", "Receipt, please"),
  ], ["shopping", "beginner"]),
  phrase("directions-ask", "Asking for directions in Korean", [
    L("화장실 어디예요?", "hwajangsil eodiyeyo?", "Where's the bathroom?"),
    L("이 길 맞아요?", "i gil majayo?", "Is this the right way?"),
    L("얼마나 걸려요?", "eolmana geollyeoyo?", "How long does it take?"),
    L("여기서 가까워요?", "yeogiseo gakkawoyo?", "Is it close from here?"),
    L("지하철역 어디예요?", "jihacheolyeok eodiyeyo?", "Where's the subway station?"),
    L("왼쪽으로 가세요", "oenjjogeuro gaseyo", "Go left"),
    L("직진하세요", "jikjinhaseyo", "Go straight"),
    L("여기서 내려요", "yeogiseo naeryeoyo", "I get off here"),
  ], ["travel", "directions", "beginner"]),
  phrase("subway-taxi", "Subway & taxi phrases in Korean", [
    L("환승이요", "hwanseungiyo", "Transfer, please"),
    L("몇 호선이에요?", "myeot hoseonieyo?", "Which line is it?"),
    L("종점 가요?", "jongjeom gayo?", "Does this go to the last stop?"),
    L("택시 불러 주세요", "taeksi bulleo juseyo", "Please call a taxi"),
    L("여기로 가 주세요", "yeogiro ga juseyo", "Please go here"),
    L("여기서 세워 주세요", "yeogiseo sewo juseyo", "Please stop here"),
    L("요금 얼마예요?", "yogeum eolmayeyo?", "How much is the fare?"),
    L("천천히 가 주세요", "cheoncheonhi ga juseyo", "Please drive slowly"),
  ], ["travel", "transport", "beginner"]),
  phrase("hotel-checkin", "Hotel check-in phrases in Korean", [
    L("체크인 할게요", "chekeuin halgeyo", "I'd like to check in"),
    L("예약했어요", "yeyakhaesseoyo", "I have a reservation"),
    L("와이파이 비밀번호요?", "waipai bimilbeonhoyyo?", "Wi‑Fi password?"),
    L("조식 몇 시예요?", "josik myeot siyeyo?", "What time is breakfast?"),
    L("수건 더 주세요", "sugeon deo juseyo", "More towels, please"),
    L("체크아웃은 몇 시예요?", "chekeuausoneun myeot siyeyo?", "Checkout time?"),
    L("짐 보관해 주세요", "jim bogwanhae juseyo", "Please hold my luggage"),
    L("영수증 부탁해요", "yeongsujeung butakhaeyo", "Receipt, please"),
  ], ["travel", "hotel", "beginner"]),
  phrase("phone-texting", "Phone & texting phrases in Korean", [
    L("전화해도 돼?", "jeonhwahaedo dwae?", "Can I call you?"),
    L("문자 보낼게", "munja bonaelge", "I'll text you"),
    L("통화 가능해?", "tonghwa ganeunghae?", "Can you talk?"),
    L("나중에 전화할게", "najunge jeonhwahalge", "I'll call later"),
    L("카톡했어", "katokaesseo", "I sent a KakaoTalk"),
    L("읽씹하지 마", "ilkssiphaji ma", "Don't leave me on read"),
    L("답장 기다려", "dapjang gidaryeo", "Wait for my reply"),
    L("배터리가 없어", "baeteoriga eopseo", "My battery is dead"),
  ], ["daily", "tech", "beginner"]),
  phrase("weather-smalltalk", "Weather small talk in Korean", [
    L("날씨 좋다", "nalssi jota", "Nice weather"),
    L("오늘 춥다", "oneul chupta", "It's cold today"),
    L("비 온다", "bi onda", "It's raining"),
    L("더워서 죽겠다", "deowoseo jukgetda", "It's so hot"),
    L("미세먼지 심해", "misemeonji simhae", "Fine dust is bad"),
    L("우산 있어?", "usan isseo?", "Do you have an umbrella?"),
    L("따뜻해졌어", "ttatteuthaejyeosseo", "It got warmer"),
    L("바람 많이 분다", "baram mani bunda", "It's really windy"),
  ], ["weather", "smalltalk", "beginner"]),
  phrase("weekend-plans", "Weekend plan phrases in Korean", [
    L("주말에 뭐 해?", "jumare mwo hae?", "What are you doing this weekend?"),
    L("영화 볼래?", "yeonghwa bollae?", "Want to watch a movie?"),
    L("밥 먹으러 갈까?", "bap meogeureo galkka?", "Shall we go eat?"),
    L("집에서 쉴래", "jibeseo swillae", "I want to rest at home"),
    L("약속 있어", "yaksok isseo", "I have plans"),
    L("시간 되면 연락해", "sigan doemyeon yeollakhae", "Text me if you're free"),
    L("다음에 하자", "daeume haja", "Let's do it next time"),
    L("재밌겠다", "jaemitgetda", "That sounds fun"),
  ], ["meetup", "daily", "beginner"]),
  phrase("compliments", "Compliment phrases in Korean", [
    L("잘한다", "jalhanda", "You're good at that"),
    L("멋있다", "meositda", "That's cool / stylish"),
    L("예쁘다", "yeppeuda", "You're pretty"),
    L("잘 어울려", "jal eoullyeo", "It suits you"),
    L("센스 있다", "senseu itda", "You have good taste"),
    L("대단해", "daedanhae", "Amazing"),
    L("부럽다", "bureopda", "I'm jealous (in a good way)"),
    L("진짜 잘했어", "jinjja jalhaesseo", "You did really well"),
  ], ["emotion", "spoken", "beginner"]),
  phrase("encouragement", "Cheer someone on in Korean", [
    L("화이팅", "hwaiting", "You got this"),
    L("할 수 있어", "hal su isseo", "You can do it"),
    L("걱정 마", "geokjeong ma", "Don't worry"),
    L("천천히 해", "cheoncheonhi hae", "Take it slow"),
    L("괜찮아질 거야", "gwaenchanajil geoya", "It'll be okay"),
    L("수고했어", "sugohaesseo", "Good work / you worked hard"),
    L("힘내", "himnae", "Cheer up"),
    L("잘될 거야", "jaldoel geoya", "It'll work out"),
  ], ["emotion", "spoken", "beginner"]),
  phrase("disagree-soft", "Soft disagreement phrases in Korean", [
    L("글쎄", "geulsse", "Well… / I'm not sure"),
    L("아닌 것 같아", "anin geot gata", "I don't think so"),
    L("조금 달라", "jogeum dalla", "It's a bit different"),
    L("그래도…", "geuraedo…", "Still… / Even so…"),
    L("내 생각엔", "nae saenggagen", "In my opinion"),
    L("그건 좀…", "geugeon jom…", "That's a bit…"),
    L("한번 더 생각해 봐", "hanbeon deo saenggakhae bwa", "Think about it again"),
    L("동의하기 어려워", "donguihagi eoryeowo", "Hard to agree"),
  ], ["opinion", "spoken", "intermediate"]),
  phrase("work-messages", "Work chat phrases in Korean", [
    L("확인했습니다", "hwaginhaetseumnida", "Got it / Confirmed"),
    L("공유드립니다", "gongyudeurimnida", "Sharing this with you"),
    L("회신 부탁드립니다", "hoesin butakdeurimnida", "Please reply"),
    L("검토해 주세요", "geomtohae juseyo", "Please review"),
    L("오늘 중으로 보낼게요", "oneul jungeuro bonaelgeyo", "I'll send it today"),
    L("미팅 가능하세요?", "miting ganeunghaseyo?", "Are you free for a meeting?"),
    L("잠시만요", "jamsimanyo", "One moment"),
    L("수고하셨습니다", "sugohasyeotseumnida", "Thank you for your work"),
  ], ["work", "polite", "intermediate"]),
  phrase("doctor-visit", "Clinic visit phrases in Korean", [
    L("예약했어요", "yeyakhaesseoyo", "I have an appointment"),
    L("머리가 아파요", "meoriga apayo", "I have a headache"),
    L("열이 나요", "yeori nayo", "I have a fever"),
    L("언제부터예요?", "eonjebuteoyeyo?", "Since when?"),
    L("처방전 주세요", "cheobangjeon juseyo", "Prescription, please"),
    L("약 어디서 받아요?", "yak eodiseo badayo?", "Where do I get medicine?"),
    L("보험 되나요?", "boheom doenayo?", "Is insurance accepted?"),
    L("다음 예약할게요", "daeum yeyakhalgeyo", "I'll book a follow-up"),
  ], ["health", "beginner"]),
  phrase("pharmacy", "Pharmacy phrases in Korean", [
    L("감기약 주세요", "gamgiyak juseyo", "Cold medicine, please"),
    L("진통제 있어요?", "jintongje isseoyo?", "Do you have painkillers?"),
    L("하루에 몇 번 먹어요?", "harue myeot beon meogeoyo?", "How many times a day?"),
    L("식후에 드세요", "sikhue deuseyo", "Take after meals"),
    L("알레르기 있어요", "allereugi isseoyo", "I have an allergy"),
    L("어린이 약이에요", "eorini yagieyo", "It's children's medicine"),
    L("연고 주세요", "yeonggo juseyo", "Ointment, please"),
    L("이거 맞아요?", "igeo majayo?", "Is this the right one?"),
  ], ["health", "beginner"]),
  phrase("bank-atm", "Bank & ATM phrases in Korean", [
    L("계좌 만들고 싶어요", "gyejwa mandeulgo sipeoyo", "I want to open an account"),
    L("출금할게요", "chulgeumhalgeyo", "I'd like to withdraw"),
    L("입금이요", "ipgeumiyo", "Deposit"),
    L("이체해 주세요", "ichehae juseyo", "Please transfer"),
    L("잔액 확인이요", "janaek hwaginyo", "Balance check"),
    L("비밀번호 잊어버렸어요", "bimilbeonho ijeobeoryeosseoyo", "I forgot my PIN"),
    L("카드 분실했어요", "kadeu bunsilhaesseoyo", "I lost my card"),
    L("환전할 수 있어요?", "hwanjeonhal su isseoyo?", "Can I exchange money?"),
  ], ["money", "daily", "beginner"]),
  phrase("dating-soft", "Dating / soft talk phrases in Korean", [
    L("오늘 즐거웠어", "oneul jeulgeowosseo", "I had fun today"),
    L("또 만나자", "tto mannaja", "Let's meet again"),
    L("보고 싶었어", "bogo sipeosseo", "I missed you"),
    L("괜찮으면 커피 할래?", "gwaenchanheumyeon keopi hallae?", "Coffee if you're free?"),
    L("너랑 있으면 편해", "neorang isseumyeon pyeonhae", "I feel comfortable with you"),
    L("답장 늦어서 미안", "dapjang neujeoseo mian", "Sorry for the late reply"),
    L("내일 어때?", "naeil eottae?", "How about tomorrow?"),
    L("조심히 들어가", "josimhi deureoga", "Get home safe"),
  ], ["emotion", "spoken", "beginner"]),
  phrase("kdrama-react", "K-drama reaction phrases in Korean", [
    L("미쳤다", "michyeotda", "Insane / crazy good"),
    L("소름 돋아", "soreum doda", "Goosebumps"),
    L("눈물 나", "nunmul na", "I'm tearing up"),
    L("반전이다", "banjeonida", "Plot twist"),
    L("연기 진짜 잘해", "yeonggi jinjja jalhae", "Acting is so good"),
    L("다음 화 언제야?", "daeum hwa eonjeya?", "When's the next episode?"),
    L("스포 하지 마", "seupo haji ma", "No spoilers"),
    L("또 보게 돼", "tto boge dwae", "I keep rewatching"),
  ], ["kcontent", "spoken", "beginner"]),
  phrase("study-korean", "Study Korean phrases", [
    L("오늘 뭐 공부해?", "oneul mwo gongbuhae?", "What are you studying today?"),
    L("발음이 어려워", "bareumi eoryeowo", "Pronunciation is hard"),
    L("이거 무슨 뜻이야?", "igeo museun tteusiya?", "What does this mean?"),
    L("예문 있어?", "yemun isseo?", "Got an example sentence?"),
    L("복습하자", "bokseuphaja", "Let's review"),
    L("단어 외웠어", "daneo oewosseo", "I memorized the words"),
    L("말하기 연습하자", "malhagi yeonseuphaja", "Let's practice speaking"),
    L("실수해도 괜찮아", "silsuhaedo gwaenchana", "Mistakes are okay"),
  ], ["study", "beginner"]),
  phrase("party-invite", "Party & invite phrases in Korean", [
    L("이번 주 파티 할 건데", "ibeon ju pati hal geonde", "I'm having a party this week"),
    L("올 수 있어?", "ol su isseo?", "Can you come?"),
    L("몇 시쯤?", "myeot sijjeum?", "Around what time?"),
    L("뭐 가져갈까?", "mwo gajyeogalkka?", "What should I bring?"),
    L("즐거웠어 고마워", "jeulgeowosseo gomawo", "Thanks, that was fun"),
    L("다음에 또 하자", "daeume tto haja", "Let's do it again"),
    L("늦을 것 같아", "neujeul geot gata", "I might be late"),
    L("먼저 갈게", "meonjeo galge", "I'm heading out first"),
  ], ["meetup", "spoken", "beginner"]),
  phrase("apology-fix", "Formal apology phrases in Korean", [
    L("죄송합니다", "joesonghamnida", "I'm sorry"),
    L("제가 실수했습니다", "jega silsuhaetseumnida", "I made a mistake"),
    L("양해 부탁드립니다", "yanghae butakdeurimnida", "Please understand"),
    L("다시는 안 그러겠습니다", "dasineun an geureogetseumnida", "It won't happen again"),
    L("불편을 드려 죄송합니다", "bulpyeoneul deuryeo joesonghamnida", "Sorry for the inconvenience"),
    L("확인이 부족했습니다", "hwagini bujokhaetseumnida", "I didn't check carefully enough"),
    L("바로 수정하겠습니다", "baro sujeonghagetseumnida", "I'll fix it right away"),
    L("다시 한번 사과드립니다", "dasi hanbeon sagwadeurimnida", "I apologize again"),
  ], ["polite", "work", "intermediate"]),
  phrase("delivery-receive", "Delivery receive phrases in Korean", [
    L("택배 왔어요", "taekbae wasseoyo", "A package arrived"),
    L("문 앞에 두세요", "mun ape duseyo", "Leave it at the door"),
    L("경비실에 맡겨 주세요", "gyeongbisire matgyeo juseyo", "Leave it at the guard office"),
    L("지금 없어요", "jigeum eopseoyo", "I'm not home now"),
    L("내일 다시 와 주세요", "naeil dasi wa juseyo", "Please come again tomorrow"),
    L("서명할게요", "seomyeonghalgeyo", "I'll sign"),
    L("송장 번호 있어요?", "songjang beonho isseoyo?", "Do you have the tracking number?"),
    L("감사합니다", "gamsahamnida", "Thank you"),
  ], ["daily", "home", "beginner"]),
  phrase("gym-fitness", "Gym phrases in Korean", [
    L("운동하러 갈래?", "undonghareo gallae?", "Want to work out?"),
    L("오늘 하체 하는 날", "oneul hache haneun nal", "Leg day today"),
    L("기구 쓰세요?", "gigu sseuseyo?", "Are you using this machine?"),
    L("세트 남았어요?", "seteu namasseoyo?", "Sets left?"),
    L("물 마시고 올게", "mul masigo olge", "I'll grab water"),
    L("스트레칭부터 하자", "seuteurechingbuteo haja", "Let's stretch first"),
    L("힘드네", "himdeune", "This is tough"),
    L("오늘도 수고했어", "oneuldo sugohaesseo", "Good job today"),
  ], ["hobby", "health", "beginner"]),
  phrase("beauty-salon", "Salon & beauty phrases in Korean", [
    L("예약했는데요", "yeyakhaenneundeyo", "I have a reservation"),
    L("짧게 잘라 주세요", "jjalge jalla juseyo", "Please cut it short"),
    L("염색하고 싶어요", "yeomsaekhago sipeoyo", "I want to dye my hair"),
    L("펌 할 수 있어요?", "peom hal su isseoyo?", "Can I get a perm?"),
    L("앞머리만 해주세요", "apmeoriman haejuseyo", "Just bangs, please"),
    L("자연스럽게 해주세요", "jayeonseureopge haejuseyo", "Make it natural"),
    L("얼마예요?", "eolmayeyo?", "How much is it?"),
    L("카드로 할게요", "kadeuro halgeyo", "Card, please"),
  ], ["beauty", "daily", "beginner"]),
  phrase("movie-theater", "Movie theater phrases in Korean", [
    L("표 두 장요", "pyo du jangyo", "Two tickets"),
    L("저녁 회차요", "jeonyeok hoechayo", "Evening showing"),
    L("커플석 있어요?", "keopeulseok isseoyo?", "Couple seats?"),
    L("팝콘이랑 콜라요", "papkonirang kollayo", "Popcorn and cola"),
    L("자막이에요?", "jamagieyo?", "Is it subtitled?"),
    L("자리 안내해 주세요", "jari annaehae juseyo", "Please show me the seats"),
    L("재밌었다", "jaemisseotda", "That was fun"),
    L("다음엔 뭐 볼까?", "daeumen mwo bolkka?", "What should we watch next?"),
  ], ["entertainment", "beginner"]),
  phrase("airport-basics", "Airport basics in Korean", [
    L("탑승구 어디예요?", "tapseunggu eodiyeyo?", "Where's the gate?"),
    L("수하물 맡기려고요", "suhamul matgiryeogoyo", "I'd like to check bags"),
    L("기내 반입이에요", "ginaebanibieyo", "Carry-on only"),
    L("탑승권 보여 주세요", "tapseunggwon boyeo juseyo", "Boarding pass, please"),
    L("연착인가요?", "yeonchagingayo?", "Is it delayed?"),
    L("환승이에요", "hwanseungieyo", "I'm transferring"),
    L("출국 심사 어디예요?", "chulguk simsa eodiyeyo?", "Where is departure immigration?"),
    L("면세점 아직 열려요?", "myeonsejeom ajik yeollyeoyo?", "Is duty-free still open?"),
  ], ["travel", "beginner"]),
  phrase("rent-house", "Renting phrases in Korean", [
    L("월세 얼마예요?", "wolse eolmayeyo?", "What's the monthly rent?"),
    L("보증금은요?", "bojeunggeumeunyo?", "And the deposit?"),
    L("관리비 포함이에요?", "gwallibi pohamieyo?", "Is maintenance included?"),
    L("언제부터 가능해요?", "eonjebuteo ganeunghaeyo?", "Available from when?"),
    L("계약서 볼 수 있어요?", "gyeyakseo bol su isseoyo?", "Can I see the contract?"),
    L("옵션이 뭐예요?", "opsyeoni mwoyeyo?", "What furniture is included?"),
    L("주변에 편의점 있어요?", "jubyeone pyeonuijeom isseoyo?", "Is there a convenience store nearby?"),
    L("생각 좀 해 볼게요", "saenggak jom hae bolgeyo", "I'll think about it"),
  ], ["housing", "intermediate"]),
  phrase("convenience-store", "Convenience store phrases in Korean", [
    L("봉지 주세요", "bongji juseyo", "Bag, please"),
    L("데워 주세요", "dewo juseyo", "Please heat this up"),
    L("젓가락 있어요?", "jeotgarak isseoyo?", "Chopsticks?"),
    L("결제할게요", "gyeoljehalgeyo", "I'll pay"),
    L("포인트 적립이요", "pointeu jeogibiyo", "Points, please"),
    L("담배 있어요?", "dambae isseoyo?", "Do you sell cigarettes?"),
    L("아이스커피 하나요", "aiseukeopi hanayo", "One iced coffee"),
    L("영수증 필요 없어요", "yeongsujeung piryo eopseoyo", "No receipt"),
  ], ["daily", "food", "beginner"]),
  phrase("classroom-talk", "Classroom talk phrases in Korean", [
    L("질문 있어요", "jilmun isseoyo", "I have a question"),
    L("다시 한번 설명해 주세요", "dasi hanbeon seolmyeonghae juseyo", "Please explain again"),
    L("칠판 잘 안 보여요", "chilpan jal an boyeoyo", "I can't see the board well"),
    L("조별 활동이에요?", "jobyeol hwaldongieyo?", "Is this group work?"),
    L("발표할게요", "balpyohalgeyo", "I'll present"),
    L("숙제 언제까지예요?", "sukje eonjekkajiyeyo?", "When is homework due?"),
    L("지각해서 죄송해요", "jigakhaeseo joesonghaeyo", "Sorry I'm late"),
    L("이해했어요", "ihaehaesseoyo", "I understand"),
  ], ["school", "beginner"]),
  phrase("friend-hangout", "Friend hangout phrases in Korean", [
    L("심심해", "simsimhae", "I'm bored"),
    L("뭐 먹을래?", "mwo meogeullae?", "What do you want to eat?"),
    L("집에 갈래?", "jibe gallae?", "Want to go home?"),
    L("한잔할래?", "hanjanhallae?", "Want a drink?"),
    L("사진 찍자", "sajin jjikja", "Let's take a photo"),
    L("분위기 좋다", "bunwigi jota", "Nice vibe"),
    L("배고파 죽겠어", "baegopa jukgesseo", "I'm starving"),
    L("오늘 굿나잇", "oneul gusnait", "Good night"),
  ], ["spoken", "daily", "beginner"]),
  phrase("customer-service", "Customer service phrases in Korean", [
    L("교환하고 싶어요", "gyohwanhago sipeoyo", "I'd like to exchange this"),
    L("환불 되나요?", "hwanbul doenayo?", "Can I get a refund?"),
    L("영수증 없어요", "yeongsujeung eopseoyo", "I don't have the receipt"),
    L("불량인 것 같아요", "bullyangin geot gatayo", "I think it's defective"),
    L("AS 받으려면요?", "eieseue bateuryeomyeonyo?", "How do I get after-service?"),
    L("담당자 바꿔 주세요", "damdangja bakkwo juseyo", "Please get me the manager"),
    L("언제 처리돼요?", "eonje cheoridwaeyo?", "When will it be handled?"),
    L("문자로 알려 주세요", "munjaro allyeo juseyo", "Please text me updates"),
  ], ["shopping", "intermediate"]),
  phrase("moving-day", "Moving day phrases in Korean", [
    L("이사업체 불렀어요", "isasieopche bulleosseoyo", "I called movers"),
    L("박스가 더 필요해요", "bakseuga deo piryohaeyo", "I need more boxes"),
    L("짐이 많아요", "jimi manayo", "There's a lot of stuff"),
    L("엘리베이터 예약했어요", "ellibeiteo yeyakhaesseoyo", "I reserved the elevator"),
    L("깨지기 쉬워요", "kkaejigi swiwoyo", "It's fragile"),
    L("어디에 둘까요?", "eodie dulkkayo?", "Where should I put this?"),
    L("쓰레기 분리해 주세요", "sseuregi bunrihae juseyo", "Please sort the trash"),
    L("수고하셨어요", "sugohasyeosseoyo", "Thank you for your hard work"),
  ], ["home", "daily", "intermediate"]),
  phrase("emergency-help", "Emergency help phrases in Korean", [
    L("도와주세요", "dowajuseyo", "Please help"),
    L("경찰 불러 주세요", "gyeongchal bulleo juseyo", "Call the police"),
    L("병원 어디에 있어요?", "byeongwon eodie isseoyo?", "Where is a hospital?"),
    L("길을 잃었어요", "gireul ireosseoyo", "I'm lost"),
    L("지갑을 잃어버렸어요", "jigabeul ireobeoryeosseoyo", "I lost my wallet"),
    L("응급상황이에요", "eunggeupsanghwangieyo", "It's an emergency"),
    L("영어 하세요?", "yeongeo haseyo?", "Do you speak English?"),
    L("통역 필요해요", "tongyeok piryohaeyo", "I need an interpreter"),
  ], ["travel", "emergency", "beginner"]),
  phrase("birthday-celebrate", "Birthday phrases in Korean", [
    L("생일 축하해", "saengil chukahae", "Happy birthday"),
    L("생일 축하해요", "saengil chukahaeyo", "Happy birthday (polite)"),
    L("선물 준비했어", "seonmul junbihaesseo", "I got you a gift"),
    L("케이크 자르자", "keikeu jareuja", "Let's cut the cake"),
    L("소원 빌어", "sowon bireo", "Make a wish"),
    L("파티 하자", "pati haja", "Let's party"),
    L("나이 한 살 더 먹었다", "nai han sal deo meogeotda", "Another year older"),
    L("오늘 주인공이야", "oneul juingongiya", "You're the star today"),
  ], ["celebration", "spoken", "beginner"]),
  phrase("office-smalltalk", "Office small talk in Korean", [
    L("오늘 회의 있어요?", "oneul hoeui isseoyo?", "Is there a meeting today?"),
    L("메일 보냈어요", "meil bonaesseoyo", "I sent an email"),
    L("이거 검토해 주세요", "igeo geomtohae juseyo", "Please review this"),
    L("마감이 언제예요?", "magami eonjeyeyo?", "When is the deadline?"),
    L("잠깐 괜찮으세요?", "jamkkan gwaenchaneuseyo?", "Do you have a moment?"),
    L("회의실 비었어요?", "hoeui sil bieosseoyo?", "Is the meeting room free?"),
    L("오늘 야근해요", "oneul yageunhaeyo", "I'm working overtime today"),
    L("수고 많으셨어요", "sugo maneusyeosseoyo", "You've worked hard"),
  ], ["work", "spoken", "intermediate"]),
  phrase("rainy-day", "Rainy day phrases in Korean", [
    L("우산 있어요?", "usan isseoyo?", "Do you have an umbrella?"),
    L("비 와요", "bi wayo", "It's raining"),
    L("우산 빌려줄래?", "usan billyeojullae?", "Can I borrow your umbrella?"),
    L("길이 미끄러워요", "giri mikkeureowoyo", "The road is slippery"),
    L("비 그칠 때까지 기다릴게요", "bi geuchil ttaekkaji gidarilgeyo", "I'll wait until it stops raining"),
    L("옷이 젖었어요", "osi jeojeosseoyo", "My clothes got wet"),
    L("날씨 때문에 늦었어요", "nalssi ttaemune neujeosseoyo", "I'm late because of the weather"),
    L("실내로 들어가요", "sillaero deureogayo", "Let's go inside"),
  ], ["weather", "daily", "beginner"]),
  phrase("photo-selfie", "Photo & selfie phrases in Korean", [
    L("사진 찍어 줄래?", "sajin jjigeo jullae?", "Can you take a photo?"),
    L("같이 찍자", "gachi jjikja", "Let's take one together"),
    L("하나 둘 셋!", "hana dul set!", "One, two, three!"),
    L("다시 찍자", "dasi jjikja", "Let's retake it"),
    L("필터 쓸까?", "pilteo sseulkka?", "Want to use a filter?"),
    L("여기로 와 봐", "yeogiro wa bwa", "Come over here"),
    L("웃어 봐", "useo bwa", "Smile"),
    L("인스타에 올릴게", "inseutae ollilge", "I'll post it on Instagram"),
  ], ["daily", "social", "beginner"]),
  phrase("laundry-home", "Laundry & home chores in Korean", [
    L("빨래해야 해", "ppallaehaeya hae", "I need to do laundry"),
    L("세제 어디 있어?", "seje eodi isseo?", "Where's the detergent?"),
    L("건조기 돌려도 돼?", "geonjogi dollyeodo dwae?", "Can I use the dryer?"),
    L("옷 널어 놓을게", "ot neoreo noheulge", "I'll hang the clothes"),
    L("청소 좀 하자", "cheongso jom haja", "Let's clean a bit"),
    L("쓰레기 버려 줄래?", "sseuregi beoryeo jullae?", "Can you take out the trash?"),
    L("설거지할게", "seolgeojihalge", "I'll do the dishes"),
    L("바닥 닦았어", "badak dakkasseo", "I mopped the floor"),
  ], ["home", "daily", "beginner"]),
  phrase("ordering-delivery", "Food delivery phrases in Korean", [
    L("배달 주문할게요", "baedal jumunhalgeyo", "I'd like to order delivery"),
    L("주소가 여기예요", "jusoga yeogiyeyo", "Here's the address"),
    L("문 앞에 놔 주세요", "mun ape nwa juseyo", "Leave it at the door"),
    L("벨 누르지 마세요", "bel nureuji maseyo", "Please don't ring the bell"),
    L("도착하면 연락 주세요", "dochakhamyeon yeollak juseyo", "Text me when you arrive"),
    L("배달비 얼마예요?", "baedalbi eolmayeyo?", "How much is the delivery fee?"),
    L("아직 안 왔어요", "ajik an wasseoyo", "It hasn't arrived yet"),
    L("잘 받았어요", "jal badasseoyo", "I received it, thanks"),
  ], ["food", "daily", "beginner"]),
  phrase("meeting-friends", "Meeting friends phrases in Korean", [
    L("어디서 볼까?", "eodiseo bolkka?", "Where should we meet?"),
    L("지금 출발해", "jigeum chulbalhae", "I'm leaving now"),
    L("거의 다 왔어", "geoui da wasseo", "I'm almost there"),
    L("입구에서 만나", "ipgueseo manna", "Meet at the entrance"),
    L("늦을 것 같아", "neujeul geot gata", "I might be late"),
    L("자리 맡아 줄래?", "jari mata jullae?", "Can you save a seat?"),
    L("먼저 주문해도 돼?", "meonjeo jumunhaedo dwae?", "Can I order first?"),
    L("다음에 또 만나자", "daeume tto mannaja", "Let's hang out again"),
  ], ["social", "spoken", "beginner"]),
  phrase("study-cafe", "Study café phrases in Korean", [
    L("공부하러 왔어", "gongbuhareo wasseo", "I came to study"),
    L("자리 있어요?", "jari isseoyo?", "Is there a seat?"),
    L("콘센트 있는 자리요", "konsenteu inneun jariyo", "A seat with an outlet, please"),
    L("와이파이 돼요?", "waipai dwaeyo?", "Does Wi-Fi work?"),
    L("조금 조용히 해 주세요", "jogeum joyonghi hae juseyo", "Please keep it a bit quieter"),
    L("몇 시간 이용할 거예요", "myeot sigan iyonghal geoyeyo", "I'll stay for a few hours"),
    L("음료는 셀프예요?", "eumnyoneun selpeuyeyo?", "Is drinks self-serve?"),
    L("짐 두고 나가도 돼요?", "jim dugo nagado dwaeyo?", "Can I leave my stuff and go out?"),
  ], ["study", "cafe", "beginner"]),
  phrase("pet-care", "Pet care phrases in Korean", [
    L("강아지 키워요", "gangaji kiwoyo", "I have a dog"),
    L("산책 갈래?", "sanchaek gallae?", "Want to go for a walk?"),
    L("사료 주세요", "saryo juseyo", "Pet food, please"),
    L("동물병원 어디예요?", "dongmulbyeongwon eodiyeyo?", "Where's the vet?"),
    L("예방접종 했어요", "yebangjeopjong haesseoyo", "I got the vaccines done"),
    L("물그릇 채워 줘", "mulgeureut chaewo jwo", "Fill the water bowl"),
    L("배변 패드 갈았어", "baebyeon paedeu garasseo", "I changed the puppy pad"),
    L("쓰다듬어도 돼요?", "sseudadeumeodo dwaeyo?", "Can I pet them?"),
  ], ["daily", "pets", "beginner"]),
];

export const EXPR_WAVE_CONCEPT_BUNDLES: VocabBundle[] = [
  concept("a-vs-the-feel", "This vs that feel in Korean", [
    C("this (near me)", "이것", "igeot", "Hand pointing to a cup next to the speaker"),
    C("that (near you)", "그것", "geugeot", "Hand pointing to a cup near the listener"),
    C("that (over there)", "저것", "jeogeot", "Hand pointing far across the room"),
    C("which one?", "어느 것", "eoneu geot", "Person choosing between two cups"),
  ], ["demonstratives", "beginner"]),
  concept("can-vs-may", "Can vs may nuance in Korean", [
    C("I can do it (ability)", "할 수 있어요", "hal su isseoyo", "Person successfully tying a knot"),
    C("You may do it (permission)", "해도 돼요", "haedo dwaeyo", "Teacher nodding yes to a student"),
    C("I can't", "못 해요", "mot haeyo", "Person failing to open a heavy lid"),
    C("You shouldn't", "하면 안 돼요", "hamyeon an dwaeyo", "No-entry sign with a person stopping"),
  ], ["modality", "beginner"]),
  concept("already-yet", "Already vs yet in Korean", [
    C("already", "이미", "imi", "Clock showing past time, task checkmark done"),
    C("already (surprise)", "벌써", "beolsseo", "Surprised face seeing finished homework early"),
    C("not yet", "아직", "ajik", "Hourglass half full, unfinished puzzle"),
    C("still", "아직도", "ajikdo", "Person still waiting on a bench"),
  ], ["time", "beginner"]),
  concept("too-also", "Also / too particles in Korean", [
    C("me too", "나도", "nado", "Two friends raising hands together"),
    C("this too", "이것도", "igeotdo", "Adding one more item to a shopping basket"),
    C("only this", "이것만", "igeotman", "One item left alone on a table"),
    C("even me", "나조차", "najocha", "Shy person pointing at self in a group"),
  ], ["particles", "beginner"]),
  concept("because-so", "Because & so in Korean", [
    C("because", "왜냐하면", "waenyahamyeon", "Person explaining with a small reason bubble"),
    C("so / therefore", "그래서", "geuraeseo", "Arrow from reason to result"),
    C("so (casual)", "그러니까", "geureonikka", "Friend concluding a chat"),
    C("that's why", "그래서요", "geuraeseoyo", "Polite summary gesture"),
  ], ["connectors", "beginner"]),
  concept("try-attempt", "Try doing in Korean", [
    C("try -ing", "해 보다", "hae boda", "Person tasting a small spoon of soup"),
    C("I'll try", "해 볼게요", "hae bolgeyo", "Person rolling up sleeves politely"),
    C("have you tried?", "해 봤어요?", "hae bwasseoyo?", "Curious friend asking about an app"),
    C("give it a try", "한번 해 봐", "hanbeon hae bwa", "Encouraging thumbs-up"),
  ], ["verbs", "beginner"]),
  concept("become-change", "Become / change in Korean", [
    C("become", "되다", "doeda", "Caterpillar to butterfly simple icon"),
    C("change (something)", "바꾸다", "bakkuda", "Swapping two colored blocks"),
    C("change (self)", "변하다", "byeonhada", "Person growing taller year marks"),
    C("become (result)", "되다", "doeda", "Student becoming a graduate with a cap"),
  ], ["verbs", "beginner"]),
  concept("must-should", "Must vs should in Korean", [
    C("must / have to", "해야 해요", "haeya haeyo", "Alarm and checklist with red must star"),
    C("should", "하는 게 좋아요", "haneun ge joayo", "Soft advice speech bubble"),
    C("don't have to", "안 해도 돼요", "an haedo dwaeyo", "Optional checkbox unchecked"),
    C("had better", "하는 편이 좋아요", "haneun pyeoni joayo", "Safer path highlighted on a map"),
  ], ["modality", "intermediate"]),
  concept("seem-looks", "Seems / looks like in Korean", [
    C("seems like", "것 같아요", "geot gatayo", "Thinking face with soft maybe cloud"),
    C("looks (appearance)", "보여요", "boyeoyo", "Mirror reflection of outfit"),
    C("sounds like", "들려요", "deullyeoyo", "Ear listening to distant music"),
    C("I feel like", "느낌이 들어요", "neukkimi deureoyo", "Hand on chest, soft intuition"),
  ], ["hedging", "intermediate"]),
  concept("while-during", "While / during in Korean", [
    C("while doing", "하면서", "hamyeonseo", "Person walking and drinking coffee"),
    C("during", "동안", "dongan", "Timeline bar labeled during class"),
    C("as soon as", "하자마자", "hajamaja", "Door opens and rain starts immediately"),
    C("before doing", "하기 전에", "hagi jeone", "Hands washing before cooking"),
  ], ["connectors", "intermediate"]),
  concept("hope-wish", "Hope & wish in Korean", [
    C("I hope", "으면 좋겠어요", "eumyeon jokesseoyo", "Person crossing fingers"),
    C("I wish", "고 싶어요", "go sipeoyo", "Looking at travel photos longingly"),
    C("I hope / wish", "바라요", "barayo", "Soft sunrise hope icon"),
    C("please let it be", "됐으면", "dwaesseumyeon", "Waiting for exam results"),
  ], ["emotion", "beginner"]),
  concept("more-most", "More & most in Korean", [
    C("more", "더", "deo", "Glass being filled higher"),
    C("the most", "가장", "gajang", "Trophy on the tallest podium"),
    C("less", "덜", "deol", "Volume slider turned down"),
    C("as much as", "만큼", "mankeum", "Two equal stacks of books"),
  ], ["degree", "beginner"]),
  concept("self-others", "Self vs others in Korean", [
    C("myself", "스스로", "seuseuro", "Person tying their own shoes"),
    C("each other", "서로", "seoro", "Two people exchanging gifts"),
    C("alone", "혼자", "honja", "One chair at a table"),
    C("together", "같이", "gachi", "Two friends walking side by side"),
  ], ["pronouns", "beginner"]),
  concept("start-finish-day", "Start & finish the day in Korean", [
    C("wake up", "일어나다", "ireonada", "Person stretching in morning light"),
    C("go to work/school", "출근하다 / 등교하다", "chulgeunhada", "Person with bag leaving home"),
    C("come home", "퇴근하다 / 하교하다", "toegeunhada", "Person arriving home evening"),
    C("go to bed", "자다", "jada", "Soft bed and moon lamp"),
  ], ["daily", "beginner"]),
  concept("ask-politely", "Asking politely in Korean", [
    C("Do you have…?", "있어요?", "isseoyo?", "Customer asking clerk about a product"),
    C("Can you…?", "해 주실 수 있어요?", "hae jusil su isseoyo?", "Polite request gesture"),
    C("Where is…?", "어디예요?", "eodiyeyo?", "Person holding a small map"),
    C("How much…?", "얼마예요?", "eolmayeyo?", "Price tag and curious face"),
  ], ["polite", "beginner"]),
  concept("know-how", "Know-how expressions in Korean", [
    C("I know", "알아요", "arayo", "Lightbulb on above a head"),
    C("I don't know", "몰라요", "mollayo", "Shrug with empty thought bubble"),
    C("I know how to", "할 줄 알아요", "hal jul arayo", "Person skillfully using chopsticks"),
    C("I learned", "배웠어요", "baewosseoyo", "Notebook with a check mark"),
  ], ["cognition", "beginner"]),
  concept("lend-borrow-scenes", "Lend vs borrow scenes", [
    C("borrow", "빌리다", "billida", "Person receiving a book from a friend"),
    C("lend", "빌려주다", "billyeojuda", "Friend handing the book over"),
    C("return", "돌려주다", "dollyeojuda", "Book being returned with a smile"),
    C("keep for now", "잠깐 쓸게", "jamkkan sseulge", "Borrower holding an umbrella briefly"),
  ], ["verbs", "beginner"]),
  concept("open-close-devices", "Open/close vs on/off", [
    C("open door", "열다", "yeolda", "Hand opening a door"),
    C("close door", "닫다", "datda", "Hand closing a door"),
    C("turn on light", "켜다", "kyeoda", "Light switch flipping on"),
    C("turn off light", "끄다", "kkeuda", "Room going soft-dark after switch off"),
  ], ["verbs", "beginner"]),
  concept("hungry-full", "Hungry vs full scenes", [
    C("hungry", "배고파요", "baegopayo", "Empty plate and rumbling tummy icon"),
    C("full", "배불러요", "baebulleoyo", "Happy full belly after a meal"),
    C("thirsty", "목말라요", "mongmallayo", "Reaching for a water bottle"),
    C("I want a snack", "간식 먹고 싶어요", "gansik meokgo sipeoyo", "Cookies on a small plate"),
  ], ["body", "beginner"]),
  concept("early-late-arrive", "Early vs late arrival", [
    C("early", "일찍", "iljjik", "Person arriving with clock showing early"),
    C("on time", "제시간에", "jesigane", "Clock hands on exact appointment"),
    C("late", "늦게", "neutge", "Person running with clock past time"),
    C("too late", "너무 늦었어요", "neomu neujeosseoyo", "Closed shop shutter"),
  ], ["time", "beginner"]),
  concept("like-prefer-love", "Like / prefer / love scenes", [
    C("like", "좋아해요", "joahaeyo", "Smiling at a coffee cup"),
    C("prefer", "더 좋아해요", "deo joahaeyo", "Choosing tea over coffee"),
    C("love", "사랑해요", "saranghaeyo", "Warm heart between two people"),
    C("don't like", "안 좋아해요", "an joahaeyo", "Politely pushing a dish aside"),
  ], ["emotion", "beginner"]),
  concept("listen-hear-scenes", "Listen vs hear scenes", [
    C("listen (actively)", "듣다", "deutda", "Headphones on, focused face"),
    C("hear (be audible)", "들리다", "deullida", "Sound waves reaching an ear"),
    C("overhear", "우연히 듣다", "uyeonhi deutda", "Catching a conversation nearby"),
    C("ignore sound", "못 들은 척", "mot deureun cheok", "Person pretending not to hear"),
  ], ["perception", "beginner"]),
  concept("see-watch-look", "See / watch / look scenes", [
    C("look at", "보다", "boda", "Eyes on a phone screen"),
    C("watch (for a while)", "지켜보다", "jikyeoboda", "Watching a pot on the stove"),
    C("sightsee", "구경하다", "gugyeonghada", "Tourist looking at a palace"),
    C("stare", "쳐다보다", "chyeodaboda", "Long stare across a café"),
  ], ["perception", "beginner"]),
  concept("remember-forget", "Remember vs forget", [
    C("remember", "기억하다", "gieokhada", "String on finger memory cue"),
    C("forget", "잊다", "itda", "Empty thought bubble"),
    C("remind me", "알려 주세요", "allyeo juseyo", "Calendar notification bell"),
    C("I almost forgot", "깜빡할 뻔했어요", "kkamppakhal ppeonhaesseoyo", "Person catching a falling note"),
  ], ["cognition", "beginner"]),
  concept("invite-refuse", "Invite & soft refuse", [
    C("Want to come?", "올래요?", "ollaeyo?", "Open invitation gesture"),
    C("Sure", "좋아요", "joayo", "Happy accepting nod"),
    C("Maybe next time", "다음에 해요", "daeume haeyo", "Polite calendar push"),
    C("I can't today", "오늘은 어려워요", "oneureun eoryeowoyo", "Busy phone calendar"),
  ], ["meetup", "beginner"]),
];

export const EXPR_WAVE_TOPIK_BUNDLES: VocabBundle[] = [
  topik("travel-verbs", "Travel verbs: TOPIK I → II", [
    T("travel", "여행가다", "yeohaenggada", "여행하다", "yeohaenghada"),
    T("depart", "떠나다", "tteonada", "출발하다", "chulbalhada"),
    T("arrive", "도착하다", "dochakhada", "이르다", "ireuda"),
    T("stay", "묵다", "mukda", "숙박하다", "sukbakhada"),
    T("book", "예약하다", "yeyakhada", "예매하다", "yemaehada"),
    T("cancel", "취소하다", "chwisohada", "취소하다", "chwisohada"),
    T("visit", "가다", "gada", "방문하다", "bangmunhada"),
    T("tour", "구경하다", "gugyeonghada", "관람하다", "gwanramhada"),
  ], ["travel"]),
  topik("emotion-formal", "Emotions (formal): TOPIK I → II", [
    T("glad", "기뻐요", "gippeoyo", "기쁩니다", "gippeumnida"),
    T("sad", "슬퍼요", "seulpeoyo", "슬픕니다", "seulpeumnida"),
    T("angry", "화나요", "hwanayo", "분합니다", "bunhamnida"),
    T("surprised", "놀라요", "nollayo", "놀랍습니다", "nollapseumnida"),
    T("worried", "걱정돼요", "geokjeongdwaeyo", "우려됩니다", "uryedoemnida"),
    T("thankful", "고마워요", "gomawoyo", "감사드립니다", "gamsadeurimnida"),
    T("sorry", "미안해요", "mianhaeyo", "송구합니다", "songguhamnida"),
    T("proud", "자랑스러워요", "jarangseureowoyo", "긍지를 느낍니다", "geungjireul neukkibnida"),
  ], ["emotion"]),
  topik("business-verbs", "Business verbs: TOPIK I → II", [
    T("meet", "만나다", "mannada", "면담하다", "myeondamhada"),
    T("discuss", "이야기하다", "iyagihada", "협의하다", "hyeobuihada"),
    T("report", "말하다", "malhada", "보고하다", "bogohada"),
    T("request", "부탁하다", "butakhada", "요청하다", "yocheonghada"),
    T("approve", "괜찮다", "gwaenchanta", "승인하다", "seunginhada"),
    T("reject", "안 된다", "an doenda", "거절하다", "geojeolhada"),
    T("schedule", "정하다", "jeonghada", "일정하다", "iljeonghada"),
    T("delay", "늦추다", "neutkuda", "연기하다", "yeongihada"),
  ], ["work"]),
  topik("news-verbs", "News verbs: TOPIK I → II", [
    T("happen", "생기다", "saenggida", "발생하다", "balsaenghada"),
    T("announce", "알리다", "allida", "발표하다", "balpyohada"),
    T("claim", "말하다", "malhada", "주장하다", "jujanghada"),
    T("deny", "아니라고 하다", "anirago hada", "부인하다", "buinhada"),
    T("investigate", "알아보다", "araboda", "수사하다", "susahada"),
    T("increase", "늘다", "neulda", "상승하다", "sangseunghada"),
    T("decrease", "줄다", "julda", "하락하다", "harakhada"),
    T("continue", "계속하다", "gyesokhada", "지속하다", "jisokhada"),
  ], ["news"]),
  topik("health-words", "Health words: TOPIK I → II", [
    T("sick", "아프다", "apeuda", "질환이 있다", "jilhwani itda"),
    T("treat", "고치다", "gochida", "치료하다", "chiryohada"),
    T("recover", "낫다", "natda", "회복하다", "hoebokhada"),
    T("prevent", "막다", "makda", "예방하다", "yebanghada"),
    T("exam (medical)", "검사하다", "geomsahada", "검진하다", "geomjinhada"),
    T("prescribe", "약 주다", "yak juda", "처방하다", "cheobanghada"),
    T("symptom", "증상", "jeungsang", "증후", "jeunghu"),
    T("healthy", "건강하다", "geonganghada", "건전하다", "geonjeonhada"),
  ], ["health"]),
  topik("school-verbs", "School verbs: TOPIK I → II", [
    T("enter school", "입학하다", "iphakhada", "입학하다", "iphakhada"),
    T("attend", "다니다", "danida", "재학하다", "jaehakhada"),
    T("take a test", "시험 보다", "siheom boda", "응시하다", "eungsihada"),
    T("pass", "합격하다", "hapgyeokhada", "통과하다", "tonggwahada"),
    T("fail", "떨어지다", "tteoreojida", "불합격하다", "bulhapgyeokhada"),
    T("submit", "내다", "naeda", "제출하다", "jechulhada"),
    T("grade", "점수 매기다", "jeomsu maegida", "채점하다", "chaejeomhada"),
    T("graduate", "졸업하다", "joreophada", "수료하다", "suryohada"),
  ], ["school"]),
  topik("environment", "Environment: TOPIK I → II", [
    T("environment", "환경", "hwangyeong", "환경", "hwangyeong"),
    T("pollution", "오염", "oyeom", "오염", "oyeom"),
    T("protect", "지키다", "jikida", "보호하다", "bohohada"),
    T("reduce", "줄이다", "jurida", "감소시키다", "gamsosikida"),
    T("recycle", "재활용하다", "jaehwaryonghada", "재활용하다", "jaehwaryonghada"),
    T("waste", "쓰레기", "sseuregi", "폐기물", "pyegimul"),
    T("climate", "날씨", "nalssi", "기후", "gihu"),
    T("energy", "에너지", "eneoji", "에너지", "eneoji"),
  ], ["society"]),
  topik("digital-life", "Digital life: TOPIK I → II", [
    T("search", "찾아보다", "chajaboda", "검색하다", "geomsaekhada"),
    T("download", "받다", "batda", "다운로드하다", "daunloduhada"),
    T("upload", "올리다", "ollida", "업로드하다", "eoploduhada"),
    T("share", "보내다", "bonaeda", "공유하다", "gongyuhada"),
    T("delete", "지우다", "jiuda", "삭제하다", "sakjehada"),
    T("log in", "들어가다", "deureogada", "로그인하다", "rogginhada"),
    T("sign up", "가입하다", "gaiphada", "등록하다", "deungnokhada"),
    T("update", "바꾸다", "bakkuda", "업데이트하다", "eopdeiteuhada"),
  ], ["tech"]),
  topik("money-verbs", "Money verbs: TOPIK I → II", [
    T("earn", "돈을 벌다", "doneul beolda", "소득을 올리다", "sodeugeul ollida"),
    T("spend", "쓰다", "sseuda", "지출하다", "jichulhada"),
    T("save", "모으다", "moeuda", "저축하다", "jeochukhada"),
    T("invest", "투자하다", "tujahada", "투자하다", "tujahada"),
    T("borrow money", "돈을 빌리다", "doneul billida", "대출받다", "daechulbatda"),
    T("repay", "갚다", "gapda", "상환하다", "sanghwanhada"),
    T("cost", "들다", "deulda", "소요되다", "soyodoeda"),
    T("profit", "이익", "iik", "수익", "suik"),
  ], ["money"]),
  topik("housing-words", "Housing: TOPIK I → II", [
    T("live", "살다", "salda", "거주하다", "geojuhada"),
    T("move", "이사하다", "isahada", "이전하다", "ijeonhada"),
    T("rent", "빌리다", "billida", "임차하다", "imchahada"),
    T("deposit", "보증금", "bojeungeum", "보증금", "bojeungeum"),
    T("contract", "계약", "gyeyak", "계약서", "gyeyakseo"),
    T("neighborhood", "동네", "dongne", "인근", "ingeun"),
    T("facility", "시설", "siseol", "편의시설", "pyeonuisisol"),
    T("commute", "출퇴근하다", "chultoegeunhada", "통근하다", "tonggeunhada"),
  ], ["housing"]),
  topik("culture-verbs", "Culture verbs: TOPIK I → II", [
    T("enjoy", "즐기다", "jeulgida", "향유하다", "hyangyuhada"),
    T("appreciate", "감상하다", "gamsanghada", "음미하다", "eummihada"),
    T("create", "만들다", "mandeulda", "창작하다", "changjakhada"),
    T("perform", "하다", "hada", "공연하다", "gongyeonhada"),
    T("exhibit", "보여 주다", "boyeo juda", "전시하다", "jeonsihada"),
    T("preserve", "지키다", "jikida", "보존하다", "bojonhada"),
    T("inherit", "물려받다", "mullyeobatda", "계승하다", "gyeseunghada"),
    T("tradition", "전통", "jeontong", "전통문화", "jeontongmunhwa"),
  ], ["culture"]),
  topik("argument-essay", "Essay verbs: TOPIK I → II", [
    T("agree", "동의하다", "donguihada", "찬성하다", "chanseonghada"),
    T("disagree", "반대하다", "bandaehada", "이의를 제기하다", "iuireul jegihada"),
    T("suggest", "제안하다", "jeanada", "제시하다", "jesihada"),
    T("emphasize", "강조하다", "gangjohada", "역설하다", "yeokseolhada"),
    T("summarize", "정리하다", "jeongnihada", "요약하다", "yoyakhada"),
    T("compare", "비교하다", "bigyohada", "대조하다", "daejohada"),
    T("conclude", "끝내다", "kkeunnaeda", "결론짓다", "gyeollonjitda"),
    T("example", "예를 들면", "yereul deulmyeon", "예컨대", "yereukonde"),
  ], ["essay"]),
  topik("polite-requests", "Polite requests: TOPIK I → II", [
    T("please do", "해 주세요", "hae juseyo", "해 주시기 바랍니다", "hae jusigi baramnida"),
    T("please wait", "기다려 주세요", "gidaryeo juseyo", "잠시만 기다려 주십시오", "jamsiman gidaryeo jusipsio"),
    T("please check", "확인해 주세요", "hwaginhae juseyo", "검토 부탁드립니다", "geomto butakdeurimnida"),
    T("please send", "보내 주세요", "bonae juseyo", "송부 부탁드립니다", "songbu butakdeurimnida"),
    T("please call", "전화해 주세요", "jeonhwahae juseyo", "연락 부탁드립니다", "yeollak butakdeurimnida"),
    T("please come", "와 주세요", "wa juseyo", "방문해 주시기 바랍니다", "bangmunhae jusigi baramnida"),
    T("please understand", "이해해 주세요", "ihaehae juseyo", "양해 부탁드립니다", "yanghae butakdeurimnida"),
    T("thank you in advance", "미리 감사해요", "miri gamsahaeyo", "미리 감사드립니다", "miri gamsadeurimnida"),
  ], ["polite"]),
  topik("time-formal", "Time words: TOPIK I → II", [
    T("now", "지금", "jigeum", "현재", "hyeonjae"),
    T("today", "오늘", "oneul", "금일", "geumil"),
    T("tomorrow", "내일", "naeil", "익일", "igil"),
    T("yesterday", "어제", "eoje", "전일", "jeonil"),
    T("recently", "요즘", "yojeum", "최근", "choegeun"),
    T("later", "나중에", "najunge", "추후", "chuhu"),
    T("immediately", "바로", "baro", "즉시", "jeuksi"),
    T("eventually", "결국", "gyeolguk", "마침내", "machimnae"),
  ], ["time"]),
  topik("people-roles", "People & roles: TOPIK I → II", [
    T("person", "사람", "saram", "인원", "inwon"),
    T("friend", "친구", "chingu", "지인", "jiin"),
    T("boss", "사장", "sajang", "대표", "daepyo"),
    T("coworker", "직장 동료", "jikjang dongnyo", "동료", "dongnyo"),
    T("customer", "손님", "sonnim", "고객", "gogaek"),
    T("student", "학생", "haksaeng", "수강생", "sugangsaeng"),
    T("teacher", "선생님", "seonsaengnim", "강사", "gangsa"),
    T("family", "가족", "gajok", "가족 구성원", "gajok guseongwon"),
  ], ["people"]),
];

export const EXPR_WAVE_SIMILAR_BUNDLES: VocabBundle[] = [
  similar("start-begin", "Start", "Begin", "시작하다", "개시하다", "sijakhada", "gaesihada", "everyday start", "formal begin", "verbs"),
  similar("finish-complete", "Finish", "Complete", "끝내다", "완료하다", "kkeunnaeda", "wanryohada", "wrap up", "fully complete", "verbs"),
  similar("help-assist", "Help", "Assist", "도와주다", "지원하다", "dowajuda", "jiwonhada", "casual help", "formal assist", "verbs"),
  similar("change-modify", "Change", "Modify", "바꾸다", "수정하다", "bakkuda", "sujeonghada", "replace/change", "edit/modify", "verbs"),
  similar("look-check", "Look", "Check", "보다", "확인하다", "boda", "hwaginhada", "look/see", "verify", "verbs"),
  similar("say-mention", "Say", "Mention", "말하다", "언급하다", "malhada", "eongeuphada", "say something", "mention briefly", "speech"),
  similar("think-consider", "Think", "Consider", "생각하다", "검토하다", "saenggakhada", "geomtohada", "think about", "review/consider", "cognition"),
  similar("need-require", "Need", "Require", "필요하다", "요구하다", "piryohada", "yoguhada", "need something", "require formally", "verbs"),
  similar("want-desire", "Want", "Desire", "원하다", "희망하다", "wonhada", "huimanghada", "want", "hope/desire", "emotion"),
  similar("use-utilize", "Use", "Utilize", "쓰다", "활용하다", "sseuda", "hwaryonghada", "use", "make use of", "verbs"),
  similar("make-produce", "Make", "Produce", "만들다", "제작하다", "mandeulda", "jejakhada", "make", "produce/create", "verbs"),
  similar("buy-order", "Buy", "Order", "사다", "주문하다", "sada", "jumunhada", "buy in store", "place an order", "shopping"),
  similar("leave-depart", "Leave", "Depart", "떠나다", "출발하다", "tteonada", "chulbalhada", "leave a place", "depart (trip)", "travel"),
  similar("arrive-reach", "Arrive", "Reach", "도착하다", "도달하다", "dochakhada", "dochaldada", "arrive", "reach a point", "travel"),
  similar("wait-standby", "Wait", "Stand by", "기다리다", "대기하다", "gidarida", "daegihada", "wait for someone", "stand by formally", "verbs"),
  similar("call-contact", "Call", "Contact", "전화하다", "연락하다", "jeonhwahada", "yeollakhada", "phone call", "get in touch", "daily"),
  similar("clean-tidy", "Clean", "Tidy up", "청소하다", "정리하다", "cheongsohada", "jeongnihada", "clean dirt", "organize/tidy", "home"),
  similar("cook-prepare-food", "Cook", "Prepare food", "요리하다", "준비하다", "yorihada", "junbihada", "cook a dish", "prepare (food)", "food"),
  similar("study-review", "Study", "Review", "공부하다", "복습하다", "gongbuhada", "bokseuphada", "study new", "review old", "school"),
  similar("rest-relax", "Rest", "Relax", "쉬다", "휴식하다", "swida", "hyusikhada", "take a break", "formal rest", "body"),
];

export const EXPR_WAVE_BUNDLES: VocabBundle[] = [
  ...EXPR_WAVE_PHRASE_BUNDLES,
  ...EXPR_WAVE_CONCEPT_BUNDLES,
  ...EXPR_WAVE_TOPIK_BUNDLES,
  ...EXPR_WAVE_SIMILAR_BUNDLES,
];
