/**
 * Cute cast wave 2 — stock up official format to ~ready pool size of phrase/sim.
 * Whole pin = ONE cast (all capybara OR all otter).
 */
import type { VocabInfographicFormatId } from "./formats";

type BundlePriority = "high" | "medium" | "low";
type CuteCell = { hangul: string; romanization: string; english: string; pose: string };
type VocabBundle = {
  id: string;
  format: VocabInfographicFormatId;
  title: string;
  count: number;
  fit: string;
  priority: BundlePriority;
  tags: string[];
  preview?: string[];
  cuteCast?: "capybara" | "otter";
  cuteCells?: CuteCell[];
};

const Cell = (
  hangul: string,
  romanization: string,
  english: string,
  pose: string,
): CuteCell => ({ hangul, romanization, english, pose });

function cute(
  slug: string,
  title: string,
  cast: "capybara" | "otter",
  cells: CuteCell[],
  tags: string[],
  priority: BundlePriority = "high",
): VocabBundle {
  if (cells.length !== 9) throw new Error(`cute-${slug} needs exactly 9 cells`);
  return {
    id: `cute-${slug}`,
    format: "cute_cast",
    title,
    count: 9,
    fit:
      cast === "otter"
        ? "Cute 3×3 sticker grid — ALL pink otter (no capybara)"
        : "Cute 3×3 sticker grid — ALL blue-hat sidekick capybara (no otter)",
    priority,
    tags: ["cute", "mascot", "spoken", cast, ...tags],
    cuteCast: cast,
    cuteCells: cells,
    preview: cells.map((c) => c.english),
  };
}

export const CUTE_WAVE2_BUNDLES: VocabBundle[] = [
  // —— capybara ×14 ——
  cute("phone-texting", "Phone texting fillers in Korean", "capybara", [
    Cell("ㅋㅋㅋ", "kkk", "lololol", "typing laugh"),
    Cell("ㅎㅎ", "hh", "hehe", "soft smile"),
    Cell("ㅇㅇ", "ungung", "yep", "quick nod"),
    Cell("ㄴㄴ", "nn", "nope", "head shake"),
    Cell("ㄱㄱ", "gg", "let's go", "point forward"),
    Cell("ㅇㅋ", "ok", "ok", "thumbs up"),
    Cell("ㄱㄷ", "gid", "wait", "pause finger"),
    Cell("ㅊㅋ", "chuk", "congrats", "tiny clap"),
    Cell("ㅂㅂ", "bb", "bye", "wave bye"),
  ], ["chat", "texting"]),
  cute("cafe-mood", "Café mood words in Korean", "capybara", [
    Cell("달달해", "daldalhae", "Sweet", "sip latte"),
    Cell("써", "sseo", "Bitter", "bitter face"),
    Cell("미지근해", "mijigeunhae", "Lukewarm", "meh shrug"),
    Cell("시원해", "siwonhae", "Refreshing", "cool breeze"),
    Cell("진해", "jinhae", "Strong brew", "bold nod"),
    Cell("연해", "yeonhae", "Weak brew", "soft tip"),
    Cell("따뜻해", "ttatteuthae", "Warm", "cozy hug cup"),
    Cell("얼음 많이", "eoreum mani", "Extra ice", "ice cubes pose"),
    Cell("포장해 주세요", "pojanghae juseyo", "To go please", "bag handoff"),
  ], ["cafe"]),
  cute("late-night", "Late-night vibes in Korean", "capybara", [
    Cell("졸려", "jollyeo", "Sleepy", "yawn"),
    Cell("잠 안 와", "jam an wa", "Can't sleep", "stare ceiling"),
    Cell("야식 각", "yasik gak", "Midnight snack time", "snack reach"),
    Cell("내일이지 뭐", "naeiriji mwo", "Tomorrow-me problem", "shrug chill"),
    Cell("불 끌게", "bul kkeulge", "Lights off", "switch flip"),
    Cell("알람 맞춰", "allam matchwo", "Set an alarm", "phone tap"),
    Cell("한숨만", "hansumman", "Just one more ep", "plead eyes"),
    Cell("내일 봐", "naeil bwa", "See you tomorrow", "sleepy wave"),
    Cell("잘자", "jalja", "Night", "blanket tuck"),
  ], ["night"]),
  cute("work-slack", "Work chat vibes in Korean", "capybara", [
    Cell("확인했어요", "hwaginhaesseoyo", "Got it / checked", "check mark pose"),
    Cell("공유할게요", "gongyuhalgeyo", "I'll share", "send file"),
    Cell("내일까지요", "naeilkkajiyo", "By tomorrow", "calendar point"),
    Cell("회의 중이요", "hoeui jungiyo", "In a meeting", "mute pose"),
    Cell("조금 늦어요", "jogeum neujeoyo", "Running a bit late", "hurry walk"),
    Cell("수고하세요", "sugohaseyo", "Hang in there", "cheer fist"),
    Cell("퇴근해요", "toegeunhaeyo", "Heading out", "bag swing"),
    Cell("내일 봐요", "naeil bwayo", "See you tomorrow", "desk wave"),
    Cell("확인 부탁드려요", "hwagin butakdeuryeoyo", "Please check", "bow tiny"),
  ], ["work"]),
  cute("metro-ride", "Metro ride words in Korean", "capybara", [
    Cell("막차예요", "makchayeyo", "Last train", "clock panic"),
    Cell("환승이요", "hwanseungiyo", "Transfer", "arrow swap"),
    Cell("앉을게요", "anjeulgeyo", "I'll sit", "sit down"),
    Cell("내려요", "naeryeoyo", "Getting off", "stand ready"),
    Cell("문 닫힙니다", "mun dathimnida", "Doors closing", "door pose"),
    Cell("혼잡해요", "honjaphaeyo", "Crowded", "squeeze cute"),
    Cell("자리 있어요?", "jari isseoyo?", "Is this free?", "point seat"),
    Cell("이어폰 끼고", "ieopon kkigo", "Earbuds in", "earbuds"),
    Cell("거의 다 왔어요", "geoui da wasseoyo", "Almost there", "hopeful lean"),
  ], ["travel"]),
  cute("gym-energy", "Gym energy words in Korean", "capybara", [
    Cell("파이팅", "paiting", "You got this", "flex tiny"),
    Cell("한 세트 더", "han seteu deo", "One more set", "count fingers"),
    Cell("물 마셔요", "mul masyeoyo", "Drink water", "bottle sip"),
    Cell("숨 고를게요", "sum goreulgeyo", "Catching breath", "hands on knees"),
    Cell("스트레칭", "seuteureching", "Stretching", "stretch arms"),
    Cell("오늘 끝", "oneul kkeut", "Done for today", "wipe sweat"),
    Cell("다리 풀려요", "dari pullyeoyo", "Legs jelly", "wobbly legs"),
    Cell("단백질!", "danbaekjil", "Protein!", "shake bottle"),
    Cell("내일도 와요", "naeildo wayo", "See you tomorrow", "towel wave"),
  ], ["fitness"]),
  cute("rainy-mood", "Rainy mood words in Korean", "capybara", [
    Cell("비 온다", "bi onda", "Rain's coming", "look up"),
    Cell("우산 있어요?", "usan isseoyo?", "Got an umbrella?", "offer umbrella"),
    Cell("젖었어요", "jeojeosseoyo", "I'm soaked", "drip drip"),
    Cell("미끄러워요", "mikkeureowoyo", "Slippery", "careful steps"),
    Cell("천둥이에요", "cheondungieyo", "Thunder", "cover ears"),
    Cell("무지개다", "mujigaeda", "Rainbow!", "sparkle point"),
    Cell("꿉꿉해", "kkupkkuphae", "Sticky humid", "fan self"),
    Cell("집에 갈래", "jibe gallae", "Wanna go home", "hood up"),
    Cell("비 그쳤어", "bi geucheosseo", "Rain stopped", "peek out"),
  ], ["weather"]),
  cute("study-focus", "Study focus words in Korean", "capybara", [
    Cell("집중해", "jipjunghae", "Focus", "serious stare"),
    Cell("한 문제만", "han munjeman", "Just one more Q", "pencil up"),
    Cell("외워야 해", "oewoya hae", "Gotta memorize", "flashcard"),
    Cell("휴식!", "hyusik", "Break!", "stretch back"),
    Cell("타이머 켜", "taimeo kyeo", "Start timer", "phone timer"),
    Cell("거의 다 했어", "geoui da haesseo", "Almost done", "checklist"),
    Cell("머리가 하얘", "meoriga hayae", "Brain blank", "dizzy stars"),
    Cell("다시 보자", "dasi boja", "Review again", "flip notes"),
    Cell("오늘 합격각", "oneul hapgyeokgak", "Passing vibes", "cheer"),
  ], ["study"]),
  cute("friend-hang", "Friend hangout words in Korean", "capybara", [
    Cell("뭐 해?", "mwo hae?", "Whatcha doing?", "peek phone"),
    Cell("나와", "nawa", "Come out", "beckon"),
    Cell("어디서 볼까", "eodiseo bolkka", "Where should we meet?", "map think"),
    Cell("늦을 듯", "neujeul deut", "Might be late", "sweat run"),
    Cell("메뉴 고르자", "menyu goreuja", "Pick a menu", "menu open"),
    Cell("사진 찍자", "sajin jjikja", "Selfie time", "camera pose"),
    Cell("계산은 내가", "gyesaneun naega", "I got the bill", "wallet out"),
    Cell("재밌었어", "jaemisseosseo", "That was fun", "heart eyes"),
    Cell("다음에 또", "daeume tto", "Again next time", "fist bump"),
  ], ["social"]),
  cute("emotion-soft", "Soft emotion words in Korean", "capybara", [
    Cell("설레", "seolle", "Butterflies", "heart flutter"),
    Cell("울컥해", "ulkkeokhae", "Getting teary", "wipe eye"),
    Cell("뿌듯해", "ppudeuthae", "Proud", "chest puff"),
    Cell("서운해", "seounhae", "A bit hurt", "pout"),
    Cell("든든해", "deundeunhae", "Reassured", "lean trust"),
    Cell("민망해", "minmanghae", "Embarrassed", "cover face"),
    Cell("든든하다", "deundeunhada", "I've got you", "pat shoulder"),
    Cell("후련해", "huryeonhae", "Relieved", "exhale smile"),
    Cell("그립다", "geuripda", "I miss it", "look far"),
  ], ["emotion"]),
  cute("shopping-vibes", "Shopping vibes in Korean", "capybara", [
    Cell("이거요", "igeoyo", "This one", "point item"),
    Cell("피팅할게요", "pitinghalgeyo", "I'll try it on", "fitting room"),
    Cell("사이즈 있어요?", "saijeu isseoyo?", "Got my size?", "size check"),
    Cell("할인인가요?", "hariningayo?", "On sale?", "tag look"),
    Cell("장바구니", "jangbaguni", "Cart", "basket hold"),
    Cell("결제할게요", "gyeoljehalgeyo", "I'll pay", "card tap"),
    Cell("영수증요", "yeongsujeungyo", "Receipt please", "receipt"),
    Cell("환불돼요?", "hwanbuldwaeyo?", "Can I return?", "box back"),
    Cell("득템!", "deuktem", "Score!", "sparkle bag"),
  ], ["shopping"]),
  cute("morning-boost", "Morning boost words in Korean", "capybara", [
    Cell("일어났어", "ireonasseo", "I'm up", "stretch"),
    Cell("커피 먼저", "keopi meonjeo", "Coffee first", "mug hug"),
    Cell("지각각", "jigakgak", "Gonna be late", "rush shoes"),
    Cell("날씨 좋다", "nalssi jota", "Nice weather", "window look"),
    Cell("씻고 올게", "ssitgo olge", "Gonna wash up", "towel"),
    Cell("준비 끝", "junbi kkeut", "Ready", "bag zip"),
    Cell("문 잠갔어?", "mun jamgasseo?", "Locked the door?", "key jingle"),
    Cell("오늘도 화이팅", "oneuldo hwaiting", "Let's go today", "fist pump"),
    Cell("출발!", "chulbal", "Let's go!", "dash out"),
  ], ["daily"]),
  cute("apology-soft", "Soft apology words in Korean", "capybara", [
    Cell("미안", "mian", "Sorry", "bow tiny"),
    Cell("진짜 미안", "jinjja mian", "Really sorry", "deep bow"),
    Cell("내 탓이야", "nae tasiya", "My bad", "hand chest"),
    Cell("깜빡했어", "kkampakhaesseo", "I forgot", "forehead tap"),
    Cell("고칠게", "gochilge", "I'll fix it", "toolbox vibe"),
    Cell("다신 안 할게", "dasin an halde", "Won't happen again", "promise pinky"),
    Cell("화났어?", "hwanasseo?", "Are you mad?", "peek careful"),
    Cell("이해해 줘", "ihaehae jwo", "Please understand", "plead paws"),
    Cell("고마워 기다려줘서", "gomawo gidaryeojwooseo", "Thanks for waiting", "relief smile"),
  ], ["polite"]),
  cute("celebrate-mini", "Mini celebration words in Korean", "capybara", [
    Cell("축하해", "chukahae", "Congrats", "confetti"),
    Cell("잘했어", "jalhaesseo", "Well done", "clap"),
    Cell("해냈다", "haenaetda", "We did it", "jump"),
    Cell("건배", "geonbae", "Cheers", "toast"),
    Cell("생일이다", "saengirida", "It's your birthday", "cake"),
    Cell("이벤트!", "ibenteu", "Event time", "party hat"),
    Cell("사진 남기자", "sajin namgija", "Photo time", "camera"),
    Cell("오늘 기념", "oneul ginyeom", "Today's special", "sparkle"),
    Cell("최고였어", "choegoyeosseo", "That was the best", "heart"),
  ], ["social"]),

  // —— otter ×14 ——
  cute("pet-talk", "Pet talk words in Korean", "otter", [
    Cell("귀여워", "gwiyeowo", "So cute", "squee cheeks"),
    Cell("착하지", "chakhaji", "Good kid", "pat head"),
    Cell("기다려", "gidaryeo", "Stay", "palm stop"),
    Cell("앉아", "anja", "Sit", "point down"),
    Cell("산책 가자", "sanchaek gaja", "Walk time", "leash"),
    Cell("간식!", "gansik", "Treat!", "snack hold"),
    Cell("목욕할 시간", "mogyokhal sigan", "Bath time", "soap bubble"),
    Cell("잘 자", "jal ja", "Sleep tight", "blanket"),
    Cell("안아줄게", "anajulge", "I'll hug you", "hug"),
  ], ["pet"]),
  cute("spicy-food", "Spicy food words in Korean", "otter", [
    Cell("매워", "maewo", "Spicy!", "fan mouth"),
    Cell("불닭각", "buldakgak", "Fire-chicken level", "sweat"),
    Cell("물!", "mul", "Water!", "gulp"),
    Cell("우유 줘", "uyu jwo", "Milk please", "milk carton"),
    Cell("덜 맵게", "deol maepge", "Less spicy", "plead"),
    Cell("중독이야", "jungdogiya", "Addictive", "heart eyes"),
    Cell("땀나", "ttamna", "I'm sweating", "wipe brow"),
    Cell("한입만 더", "hanimman deo", "One more bite", "chopsticks"),
    Cell("내일도 먹을래", "naeildo meogeullae", "Wanna eat again tomorrow", "happy full"),
  ], ["food"]),
  cute("travel-day", "Travel day words in Korean", "otter", [
    Cell("짐 챙겼어?", "jim chaenggyeosseo?", "Packed?", "suitcase"),
    Cell("여권 어디", "yeogwon eodi", "Where's my passport", "search bag"),
    Cell("체크인했어", "chekeuinhaesseo", "Checked in", "boarding pass"),
    Cell("게이트 어디야", "geiteu eodiya", "Which gate?", "look signs"),
    Cell("이륙이다", "iryugida", "Taking off", "window seat"),
    Cell("도착했어", "dochakhaesseo", "Landed", "cheer"),
    Cell("짐 찾는 중", "jim chatneun jung", "Baggage claim", "carousel wait"),
    Cell("환전할까", "hwanjeonhalkka", "Should we exchange money?", "wallet"),
    Cell("사진 찍자", "sajin jjikja", "Photo!", "landmark pose"),
  ], ["travel"]),
  cute("game-night", "Game night words in Korean", "otter", [
    Cell("한 판 더", "han pan deo", "One more round", "controller"),
    Cell("졌다", "jyeotda", "I lost", "facepalm"),
    Cell("이겼다!", "igyeotda", "I won!", "victory"),
    Cell("치트 아니야", "chiteu aniya", "Not cheating", "innocent"),
    Cell("팀 짜자", "tim jjaja", "Make teams", "point pals"),
    Cell("룰 설명해줘", "rul seolmyeonghaejwo", "Explain the rules", "rulebook"),
    Cell("내 차례", "nae charye", "My turn", "dice"),
    Cell("스낵 타임", "seunaek taim", "Snack time", "chips"),
    Cell("내일 리벤지", "naeil ribenji", "Rematch tomorrow", "fist"),
  ], ["fun"]),
  cute("healing-day", "Healing day words in Korean", "otter", [
    Cell("쉬자", "swija", "Let's rest", "lie down"),
    Cell("산책 좋아", "sanchaek joa", "Walk feels nice", "stroll"),
    Cell("햇빛 좋다", "haetbit jota", "Nice sun", "sunbathe"),
    Cell("차 한잔", "cha hanjan", "Cup of tea", "tea cup"),
    Cell("음악 틀자", "eumak teulja", "Put music on", "headphones"),
    Cell("전화 끄자", "jeonhwa kkeuja", "Phone off", "silent mode"),
    Cell("심호흡", "simhoheup", "Deep breath", "breathe"),
    Cell("괜찮아질 거야", "gwaenchanajil geoya", "It'll be okay", "soft hug"),
    Cell("오늘 나 칭찬", "oneul na chingchan", "Proud of me today", "pat self"),
  ], ["selfcare"]),
  cute("cooking-home", "Home cooking words in Korean", "otter", [
    Cell("뭐 해 먹지", "mwo hae meokji", "What to cook?", "fridge stare"),
    Cell("재료 썰자", "jaeryo sseolja", "Let's chop", "knife board"),
    Cell("간 맞춰", "gan matchwo", "Season it", "taste spoon"),
    Cell("끓인다", "kkeurinda", "Boiling", "pot steam"),
    Cell("거의 다 됐어", "geoui da dwaesseo", "Almost ready", "timer"),
    Cell("상 차리자", "sang charja", "Set the table", "plates"),
    Cell("잘 먹겠습니다", "jal meokgetseumnida", "Thanks for the meal", "hands together"),
    Cell("설거지 내가", "seolgeojji naega", "I'll wash dishes", "sponge"),
    Cell("내일 도시락", "naeil dosirak", "Lunchbox tomorrow", "bento pack"),
  ], ["food", "home"]),
  cute("weather-chat2", "Weather chat words in Korean", "otter", [
    Cell("더워 죽겠어", "deowo jukgesseo", "Dying of heat", "melt"),
    Cell("추워 떨려", "chuwo tteollyeo", "Shivering cold", "scarf"),
    Cell("바람 세다", "baram seda", "Strong wind", "hold hat"),
    Cell("미세먼지야", "misemeonjiya", "Bad air day", "mask on"),
    Cell("선크림 발라", "seonkeurim balla", "Sunscreen on", "squeeze tube"),
    Cell("우산 필수", "usan pilsu", "Umbrella needed", "umbrella"),
    Cell("단풍 예쁘다", "danpung yeppeuda", "Pretty fall leaves", "leaf hold"),
    Cell("눈사람 만들자", "nunsaram mandeulja", "Make a snowman", "snowball"),
    Cell("날씨앱 봤어?", "nalssiaeb bwasseo?", "Check the weather app?", "phone"),
  ], ["weather"]),
  cute("date-soft", "Soft date words in Korean", "otter", [
    Cell("보고 싶었어", "bogo sipeosseo", "Missed you", "heart"),
    Cell("어디 갈까", "eodi galkka", "Where to?", "think"),
    Cell("손잡을까", "sonjabeulkka", "Hold hands?", "reach paw"),
    Cell("사진 찍어도 돼?", "sajin jjigeodo dwae?", "Mind a photo?", "camera shy"),
    Cell("맛있다 진짜", "masitda jinjja", "This is so good", "share bite"),
    Cell("시간 빠르다", "sigan ppareuda", "Time flies", "clock soft"),
    Cell("다음에 또 보자", "daeume tto boja", "See you again", "wave"),
    Cell("연락할게", "yeollakhalge", "I'll text you", "phone"),
    Cell("오늘 좋았어", "oneul joasseo", "Today was nice", "blush"),
  ], ["social"]),
  cute("hospital-soft", "Clinic soft words in Korean", "otter", [
    Cell("어디가 아파요?", "eodiga apayo?", "Where does it hurt?", "concern"),
    Cell("열 있어요", "yeol isseoyo", "I have a fever", "thermometer"),
    Cell("약 먹었어요", "yak meogeosseoyo", "I took medicine", "pill"),
    Cell("처방이요", "cheobangiyo", "Prescription please", "paper"),
    Cell("보험 되나요?", "boheom doenayo?", "Insurance ok?", "card"),
    Cell("대기 중이에요", "daegi jungieyo", "Waiting", "chair wait"),
    Cell("주사 맞아요?", "jusa majayo?", "Do I need a shot?", "nervous"),
    Cell("푹 쉬세요", "puk swiseyo", "Rest well", "blanket"),
    Cell("나을 거예요", "naeul geoyeyo", "You'll get better", "encourage"),
  ], ["health"]),
  cute("office-soft2", "Office soft words in Korean", "otter", [
    Cell("메일 보냈어요", "meil bonaesseoyo", "I sent the email", "send"),
    Cell("회의실이요", "hoevisiri yo", "Meeting room", "door"),
    Cell("자료 업데이트", "jaryo eopdeiteu", "File updated", "laptop"),
    Cell("피드백 부탁", "pideubaek butak", "Feedback please", "note"),
    Cell("마감이에요", "magamieyo", "Deadline", "clock stress"),
    Cell("잠깐 쉴게요", "jamkkan swilgeyo", "Quick break", "coffee"),
    Cell("점심 드셨어요?", "jeomsim deusyeosseoyo?", "Had lunch?", "ask"),
    Cell("내일 이어서", "naeil ieoseo", "Continue tomorrow", "bookmark"),
    Cell("수고 많으셨어요", "sugo maneusyeosseoyo", "Thanks for the hard work", "bow"),
  ], ["work"]),
  cute("family-soft", "Family soft words in Korean", "otter", [
    Cell("밥 먹었어?", "bap meogeosseo?", "Did you eat?", "care"),
    Cell("일찍 들어와", "iljjik deureowa", "Come home early", "door light"),
    Cell("따뜻하게 입어", "ttatteuthage ibeo", "Dress warm", "scarf wrap"),
    Cell("전화해", "jeonhwahae", "Call me", "phone"),
    Cell("조심히 가", "josimhi ga", "Go carefully", "wave"),
    Cell("사랑해", "saranghae", "Love you", "heart"),
    Cell("보고 싶다", "bogo sipda", "I miss you", "teary soft"),
    Cell("잘 지내?", "jal jinae?", "How have you been?", "smile"),
    Cell("명절에 봐", "myeongjeore bwa", "See you for the holiday", "calendar"),
  ], ["family"]),
  cute("hobby-soft", "Hobby soft words in Korean", "otter", [
    Cell("그려볼게", "geuryeobolge", "I'll draw it", "pencil"),
    Cell("사진 보정", "sajin bojeong", "Photo edit", "tablet"),
    Cell("악기 연습", "akgi yeonseup", "Instrument practice", "notes"),
    Cell("플랜트 물", "peullaenteu mul", "Water plants", "watering"),
    Cell("퍼즐 한 조각", "peojeul han jogak", "One puzzle piece", "puzzle"),
    Cell("일기 쓸래", "ilgi sseullae", "Gonna journal", "notebook"),
    Cell("영상 찍자", "yeongsang jjikja", "Let's film", "camera"),
    Cell("레슨 있어", "reseun isseo", "I have a lesson", "bag"),
    Cell("취미 최고", "chwimi choego", "Hobbies rock", "sparkle"),
  ], ["hobby"]),
  cute("weekend-plan", "Weekend plan words in Korean", "otter", [
    Cell("주말이야", "jumariya", "It's the weekend", "cheer"),
    Cell("브런치 갈래?", "beureonchi gallae?", "Brunch?", "menu"),
    Cell("영화 보자", "yeonghwa boja", "Movie?", "popcorn"),
    Cell("낮잠 각", "natjam gak", "Nap time", "pillow"),
    Cell("청소할까", "cheongsohalkka", "Should we clean?", "broom"),
    Cell("카페 투어", "kape tueo", "Café hop", "two cups"),
    Cell("운동 갈까", "undong galkka", "Wanna work out?", "sneakers"),
    Cell("넷플 정주행", "netpeul jeongjuhaeng", "Binge watch", "couch"),
    Cell("월요일이네…", "woryoirine…", "Monday already…", "sigh soft"),
  ], ["daily"]),
  cute("encouragement", "Encouragement words in Korean", "otter", [
    Cell("할 수 있어", "hal su isseo", "You can do it", "cheer"),
    Cell("천천히 해", "cheoncheonhi hae", "Take it slow", "calm hand"),
    Cell("괜찮아", "gwaenchana", "It's okay", "soft smile"),
    Cell("잘하고 있어", "jalhago isseo", "You're doing great", "thumbs"),
    Cell("포기하지 마", "pogihaji ma", "Don't give up", "fist"),
    Cell("내가 있어", "naega isseo", "I'm here", "side hug"),
    Cell("한 걸음씩", "han georeumssik", "One step at a time", "footstep"),
    Cell("충분히 잘했어", "chungbunhi jalhaesseo", "You did enough", "pat"),
    Cell("내일은 더 나을 거야", "naeireun deo naeul geoya", "Tomorrow'll be better", "sunrise"),
  ], ["emotion"]),
];
