/** Expression SEO wave 3 — large overnight seed batch (no grids). */
import type { VocabInfographicFormatId } from "./formats";

type BundlePriority = "high" | "medium" | "low";
type PhraseLine = { hangul: string; romanization: string; english: string };
type ConceptRow = { english: string; hangul: string; romanization: string; visual: string };
type TopikRow = { english: string; topikI: { hangul: string; romanization: string }; topikII: { hangul: string; romanization: string } };
type SimilarPair = { leftEnglish: string; rightEnglish: string; leftHangul: string; rightHangul: string; leftRom: string; rightRom: string; leftNuance: string; rightNuance: string };
type VocabBundle = { id: string; format: VocabInfographicFormatId; title: string; count: number; fit: string; priority: BundlePriority; tags: string[]; preview?: string[]; conceptRows?: ConceptRow[]; phraseLines?: PhraseLine[]; similarPair?: SimilarPair; topikRows?: TopikRow[] };

function phrase(slug: string, title: string, lines: PhraseLine[], tags: string[], priority: BundlePriority = "high"): VocabBundle {
  return { id: `phrase-${slug}`, format: "phrase_stack", title, count: lines.length, fit: `Polished ${lines.length}-phrase stack — spoken Korean`, priority, tags: ["phrase", "spoken", ...tags], phraseLines: lines, preview: lines.map((l) => l.english) };
}
function concept(slug: string, title: string, rows: ConceptRow[], tags: string[], priority: BundlePriority = "high"): VocabBundle {
  return { id: `concept-${slug}`, format: "concept_rows", title, count: rows.length, fit: "Concept diagram panels — situation beats", priority, tags: ["concept", "grammar", ...tags], conceptRows: rows, preview: rows.map((r) => r.english) };
}
function topik(slug: string, title: string, rows: TopikRow[], tags: string[], priority: BundlePriority = "high"): VocabBundle {
  return { id: `topik-${slug}`, format: "topik_upgrade", title, count: rows.length, fit: `TOPIK I→II upgrade — ${rows.length} pairs`, priority, tags: ["topik", "upgrade", ...tags], topikRows: rows, preview: rows.map((r) => r.english) };
}
function similar(slug: string, leftEnglish: string, rightEnglish: string, leftHangul: string, rightHangul: string, leftRom: string, rightRom: string, leftNuance: string, rightNuance: string, theme: string, priority: BundlePriority = "high"): VocabBundle {
  return { id: `sim-${slug}`, format: "similar_split", title: `${leftEnglish} vs ${rightEnglish}`, count: 2, fit: `Near-synonyms — ${theme}: ${leftNuance} / ${rightNuance}`, priority, tags: ["similar", theme], similarPair: { leftEnglish, rightEnglish, leftHangul, rightHangul, leftRom, rightRom, leftNuance, rightNuance }, preview: [leftEnglish, rightEnglish] };
}
const L = (hangul: string, romanization: string, english: string): PhraseLine => ({ hangul, romanization, english });
const C = (english: string, hangul: string, romanization: string, visual: string): ConceptRow => ({ english, hangul, romanization, visual });
const T = (english: string, iH: string, iR: string, iiH: string, iiR: string): TopikRow => ({ english, topikI: { hangul: iH, romanization: iR }, topikII: { hangul: iiH, romanization: iiR } });

export const EXPR_WAVE3_PHRASE_BUNDLES: VocabBundle[] = [
  phrase("morning-routine", "Morning routine phrases in Korean", [
    L("일어났어요", "ireonasseoyo", "I woke up"),
    L("세수했어요", "sesuhaesseoyo", "I washed my face"),
    L("아침 먹었어요", "achim meogeosseoyo", "I ate breakfast"),
    L("출근해요", "chulgeunhaeyo", "I'm leaving for work"),
    L("지각했어요", "jigakhaesseoyo", "I'm late"),
    L("커피 마셨어요", "keopi masyeosseoyo", "I drank coffee"),
    L("날씨 확인했어요", "nalssi hwaginhaesseoyo", "I checked the weather"),
    L("준비 끝났어요", "junbi kkeunnasseoyo", "I'm ready"),
  ], ['daily']),
  phrase("night-routine", "Night routine phrases in Korean", [
    L("씻고 잘게요", "ssitgo jalgeyo", "I'll wash up and sleep"),
    L("불 끌게요", "bul kkeulgeyo", "I'll turn off the light"),
    L("알람 맞춰 주세요", "allam matchwo juseyo", "Please set an alarm"),
    L("내일 일찍 일어나요", "naeil iljjik ireonayo", "I wake up early tomorrow"),
    L("오늘 하루 힘들었어요", "oneul haru himdeureosseoyo", "Today was hard"),
    L("잘 자요", "jal jayo", "Good night"),
    L("꿈 꿔요", "kkum kkwoyo", "Sweet dreams"),
    L("폰 내려놓을게요", "pon naeryeonoheulgeyo", "I'll put the phone down"),
  ], ['daily']),
  phrase("polite-service", "Service desk phrases in Korean", [
    L("도와드리겠습니다", "dowadeurigetseumnida", "I'll help you"),
    L("잠시만 기다려 주세요", "jamsiman gidaryeo juseyo", "Please wait a moment"),
    L("확인 중입니다", "hwagin jungimnida", "I'm checking now"),
    L("이쪽으로 와 주세요", "ijjogeuro wa juseyo", "Please come this way"),
    L("작성해 주세요", "jakseonghae juseyo", "Please fill this out"),
    L("서명해 주세요", "seomyeonghae juseyo", "Please sign"),
    L("다음 분 오세요", "daeum bun oseyo", "Next person, please"),
    L("이용해 주셔서 감사합니다", "iyonghae jusyeoseo gamsahamnida", "Thanks for using our service"),
  ], ['polite']),
  phrase("lost-found", "Lost and found phrases in Korean", [
    L("지갑을 잃어버렸어요", "jigabeul ireobeoryeosseoyo", "I lost my wallet"),
    L("휴대폰을 찾아요", "hyudaeponeul chajayo", "I'm looking for my phone"),
    L("분실물 센터 어디예요?", "bunsilmul senteo eodiyeyo?", "Where is lost and found?"),
    L("여기 두셨나요?", "yeogi dusyeonnayo?", "Did you leave it here?"),
    L("주우신 분 있나요?", "juusin bun innayo?", "Did anyone pick it up?"),
    L("사례할게요", "saryehalgeyo", "I'll give a reward"),
    L("마지막으로 본 곳은요", "majimageuro bon goseunyo", "The last place I saw it was…"),
    L("찾으면 연락 주세요", "chajeumyeon yeollak juseyo", "Contact me if you find it"),
  ], ['travel']),
  phrase("fitness-gym2", "Gym talk phrases in Korean", [
    L("오늘 하체 해요", "oneul hache haeyo", "Leg day today"),
    L("세트 남았어요", "seteu namasseoyo", "I have sets left"),
    L("기구 쓰세요?", "gigu sseuseyo?", "Are you using this machine?"),
    L("사이사이 괜찮아요", "saisai gwaenchanayo", "Working in is fine"),
    L("물 좀 마셔요", "mul jom masyeoyo", "Drink some water"),
    L("스트레칭 할게요", "seuteureching halgeyo", "I'll stretch"),
    L("퍼스널 트레이닝이요", "peoseoneol teureiningiyo", "Personal training"),
    L("운동 끝났어요", "undong kkeunnasseoyo", "Workout done"),
  ], ['fitness']),
  phrase("beauty-salon2", "Salon appointment phrases in Korean", [
    L("커트만요", "keoteumanyo", "Just a cut"),
    L("염색하고 싶어요", "yeomsaekhago sipeoyo", "I want to dye it"),
    L("어깨까지 잘라 주세요", "eokkaekkaji jalla juseyo", "Cut to shoulder length"),
    L("앞머리 해 주세요", "apmeori hae juseyo", "Bangs, please"),
    L("펌 유지 기간이요?", "peom yuji giganiyo?", "How long does the perm last?"),
    L("예약 변경할게요", "yeyak byeongyeonghalgeyo", "I'll change the appointment"),
    L("스타일 이대로요", "seutail idaerooyo", "Keep this style"),
    L("건조만 해 주세요", "geonjoman hae juseyo", "Just blow-dry, please"),
  ], ['beauty']),
  phrase("movie-talk", "Movie night phrases in Korean", [
    L("영화 볼까요?", "yeonghwa bolkkayo?", "Want to watch a movie?"),
    L("팝콘 살까요?", "papkon salkkayo?", "Shall we get popcorn?"),
    L("자막으로 볼게요", "jamageuro bolgeyo", "I'll watch with subtitles"),
    L("스포 금지예요", "seupo geumjiyeyo", "No spoilers"),
    L("좌석 앞쪽이요", "jwaseok apjjogiyo", "Front seats, please"),
    L("재미있었어요", "jaemiisseosseoyo", "It was fun"),
    L("감독이 누구예요?", "gamdogi nuguyeyo?", "Who's the director?"),
    L("다시 보고 싶어요", "dasi bogo sipeoyo", "I want to watch it again"),
  ], ['culture']),
  phrase("cafe-study2", "Study café phrases in Korean", [
    L("조용한 자리 있어요?", "joyonghan jari isseoyo?", "Is there a quiet seat?"),
    L("콘센트 있는 자리요", "konsenteu inneun jariyo", "A seat with an outlet"),
    L("몇 시간 이용할게요", "myeot sigan iyonghalgeyo", "I'll stay a few hours"),
    L("음료 필수예요?", "eumnyo pilsuyeyo?", "Is a drink required?"),
    L("와이파이 비밀번호요", "waipai bimilbeonhoyyo", "Wi-Fi password?"),
    L("짐 두고 나갔다 와도 돼요?", "jim dugo nagatda wado dwaeyo?", "Can I leave my stuff and come back?"),
    L("프린트 되나요?", "peurinteu doenayo?", "Can I print?"),
    L("자리 맡아 주세요", "jari mata juseyo", "Please save my seat"),
  ], ['study']),
  phrase("delivery-app", "Delivery app phrases in Korean", [
    L("배달 앱으로 시켰어요", "baedal apeuro sikyeosseoyo", "I ordered on a delivery app"),
    L("문 앞에 놔 주세요", "mun ape nwa juseyo", "Leave it at the door"),
    L("벨 누르지 마세요", "bel nureuji maseyo", "Don't ring the bell"),
    L("도착 예정 시간요?", "dochak yejeong siganyo?", "ETA?"),
    L("리뷰 남길게", "ribyu namgilge", "I'll leave a review"),
    L("쿠폰 적용됐어요", "kupon jeogyongdwaesseoyo", "The coupon applied"),
    L("잘못 왔어요", "jalmot wasseoyo", "Wrong order arrived"),
    L("사진 찍어 주세요", "sajin jjigeo juseyo", "Please take a photo (of delivery)"),
  ], ['food']),
  phrase("bank-simple", "Bank & money phrases in Korean", [
    L("계좌 개설하고 싶어요", "gyejwa gaeseolhago sipeoyo", "I'd like to open an account"),
    L("이체할게요", "ichehalgeyo", "I'll transfer money"),
    L("잔액 확인이요", "janaek hwaginiyo", "Balance check"),
    L("비밀번호 잊어버렸어요", "bimilbeonho ijeobeoryeosseoyo", "I forgot my PIN"),
    L("카드 재발급이요", "kadeu jaebalgubiyo", "Card reissue"),
    L("환율이 얼마예요?", "hwanyuri eolmayeyo?", "What's the exchange rate?"),
    L("달러로 환전해요", "dalleoro hwanjeonhaeyo", "Exchange to dollars"),
    L("통장 주세요", "tongjang juseyo", "Passbook, please"),
  ], ['daily']),
  phrase("hospital-er", "ER / urgent care phrases in Korean", [
    L("응급이에요", "eunggeubieyo", "It's an emergency"),
    L("숨이 차요", "sumi chayo", "I can't breathe well"),
    L("피를 흘려요", "pireul heullyeoyo", "I'm bleeding"),
    L("의식이 없어요", "uisigi eopseoyo", "They're unconscious"),
    L("구급차 불러 주세요", "gugeupcha bulleo juseyo", "Call an ambulance"),
    L("알레르기 약이요", "allereugi yagiyo", "Allergy medicine"),
    L("아픈 지 오래됐어요", "apeun ji oraedwaesseoyo", "It's been hurting a while"),
    L("보험증 있어요", "boheumjeung isseoyo", "I have insurance"),
  ], ['health']),
  phrase("job-interview", "Job interview phrases in Korean", [
    L("면접 보러 왔습니다", "myeonjeop boreo watseumnida", "I'm here for an interview"),
    L("자기소개 하겠습니다", "jagisogae hagetseumnida", "I'll introduce myself"),
    L("경력이 어떻게 되세요?", "gyeongnyeogi eotteoge doeseyo?", "What's your experience?"),
    L("입사 가능일은요?", "ipsa ganeungireunyo?", "When can you start?"),
    L("연봉 협의 가능할까요?", "yeonbong hyeobui ganeunghalkkayo?", "Is salary negotiable?"),
    L("질문 있으신가요?", "jilmun isseusinkayo?", "Any questions?"),
    L("결과 알려 주세요", "gyeolgwa allyeo juseyo", "Please let me know the result"),
    L("감사합니다", "gamsahamnida", "Thank you"),
  ], ['work']),
  phrase("roommate", "Roommate phrases in Korean", [
    L("설거지 차례야", "seolgeojj charyeya", "Your turn for dishes"),
    L("빨래 돌려도 돼?", "ppallae dollyeodo dwae?", "Can I run laundry?"),
    L("공과금 나눴어?", "gonggwageum nanwosseoyo?", "Did we split utilities?"),
    L("손님 와도 돼?", "sonnim wado dwae?", "Can I have guests over?"),
    L("조용히 해야 해", "joyonghi haeya hae", "We need to be quiet"),
    L("냉장고 칸 나눠 쓰자", "naengjanggo kan nanwo sseuja", "Let's split fridge shelves"),
    L("청소 요일 정하자", "cheongso yoil jeonghaja", "Let's set cleaning days"),
    L("열쇠 하나 더 있어?", "yeolsoe hana deo isseo?", "Is there an extra key?"),
  ], ['home']),
  phrase("festival", "Festival phrases in Korean", [
    L("축제 언제예요?", "chukje eonjeyeyo?", "When is the festival?"),
    L("입장료 있어요?", "ipjangnyo isseoyo?", "Is there an entry fee?"),
    L("줄이 길어요", "juri gireoyo", "The line is long"),
    L("푸드트럭 쪽이에요", "pudeuteureok jjogieyo", "By the food trucks"),
    L("불꽃놀이 봐요", "bulkkotnori bwayo", "Watching fireworks"),
    L("기념품 살게요", "ginyeompum salgeyo", "I'll buy a souvenir"),
    L("사진 찍기 좋아요", "sajin jjikgi joayo", "Great for photos"),
    L("사람 진짜 많아요", "saram jinjja manayo", "So many people"),
  ], ['culture']),
  phrase("pet-park", "Dog park phrases in Korean", [
    L("강아지 친화적인가요?", "gangaji chinhwajeogingayo?", "Is it dog-friendly?"),
    L("목줄 필수예요?", "mokjul pilsuyeyo?", "Is a leash required?"),
    L("간식 줘도 돼요?", "gansik jwodo dwaeyo?", "Can I give treats?"),
    L("물그릇 어디 있어요?", "mulgeureut eodi isseoyo?", "Where's the water bowl?"),
    L("다른 강아지랑 놀아요", "dareun gangajirang norayo", "Playing with other dogs"),
    L("배변 치울게요", "baebyeon chiulgeyo", "I'll clean up after"),
    L("접종했어요", "jeopjonghaesseoyo", "Vaccines are done"),
    L("이름 뭐예요?", "ireum mwoyeyo?", "What's their name?"),
  ], ['pets']),
  phrase("library", "Library phrases in Korean", [
    L("회원증 만들어요", "hoewonjeung mandeureoyo", "I'll make a library card"),
    L("책 빌릴게요", "chaek billyeolgeyo", "I'll borrow a book"),
    L("반납일 언제예요?", "bannabil eonjeyeyo?", "When is it due?"),
    L("연장할 수 있어요?", "yeonjanghal su isseoyo?", "Can I renew?"),
    L("열람실 어디예요?", "yeollamsil eodiyeyo?", "Where is the reading room?"),
    L("조용히 해 주세요", "joyonghi hae juseyo", "Please be quiet"),
    L("복사 되나요?", "boksa doenayo?", "Can I photocopy?"),
    L("예약 도서요", "yeyak doseoyo", "A reserved book"),
  ], ['study']),
  phrase("haircut-chat", "Haircut chat phrases in Korean", [
    L("조금만 잘라 주세요", "jogeumman jalla juseyo", "Just a little, please"),
    L("단정하게 해 주세요", "danjeonghage hae juseyo", "Neat and tidy, please"),
    L("볼륨 살려 주세요", "bollyum sallyeo juseyo", "Add volume, please"),
    L("앞머리 내려요", "apmeori naeryeoyo", "Leave bangs down"),
    L("거울로 볼게요", "geouro bolgeyo", "I'll check in the mirror"),
    L("이대로 좋아요", "idaero joayo", "This is good as is"),
    L("샴푸만 해 주세요", "syampu man hae juseyo", "Shampoo only, please"),
    L("다음 예약할게요", "daeum yeyakhalgeyo", "I'll book next time"),
  ], ['beauty']),
  phrase("subway-etiquette", "Subway etiquette phrases in Korean", [
    L("약자석이에요", "yakjaseogieyo", "This is a priority seat"),
    L("가방 앞으로 해 주세요", "gabang apeuro hae juseyo", "Please keep bags in front"),
    L("문 쪽 비워 주세요", "mun jjok biwo juseyo", "Please clear the door area"),
    L("전화는 짧게 해 주세요", "jeonhwaneun jjalge hae juseyo", "Please keep calls short"),
    L("이어폰 써 주세요", "ieopon sseo juseyo", "Please use earphones"),
    L("자리 양보해 주세요", "jari yangbohae juseyo", "Please give up your seat"),
    L("내리실 분은 미리", "naerisil buneun miri", "Exit early if getting off"),
    L("끼지 마세요", "kkiji maseyo", "Please don't cut in"),
  ], ['travel']),
  phrase("rent-contract", "Rental contract phrases in Korean", [
    L("보증금이 얼마예요?", "bojeunggeumi eolmayeyo?", "How much is the deposit?"),
    L("월세에 뭐가 포함돼요?", "wolsee mwoga pohamdwaeyo?", "What's included in rent?"),
    L("계약서 보여 주세요", "gyeyakseo boyeo juseyo", "Please show the contract"),
    L("중개수수료요?", "junggaesusuryoyo?", "Agent fee?"),
    L("입주 가능일이요", "ipju ganeungiriyo", "Move-in date"),
    L("관리비가 별도예요?", "gwanribiga byeoldoyeyo?", "Is maintenance separate?"),
    L("반려동물 가능한가요?", "ballyeodongmul ganeunghangayo?", "Are pets allowed?"),
    L("가계약금 내요", "gageyakgeum naeyo", "I'll pay the earnest money"),
  ], ['home']),
  phrase("weather-smalltalk2", "More weather small talk in Korean", [
    L("오늘 일교차 커요", "oneul ilgycha keoyo", "Big temperature swing today"),
    L("습하네요", "seuphanayo", "It's humid"),
    L("바람 많이 불어요", "baram mani bureoyo", "It's very windy"),
    L("우산 안 가져왔어요", "usan an gajyeowasseoyo", "I didn't bring an umbrella"),
    L("미세먼지 마스크요", "misemeonji maseukeuyo", "Fine-dust mask"),
    L("봄나들이 가기 좋아요", "bomnadeuri gagi joayo", "Nice for a spring outing"),
    L("가을 하늘 예쁘네요", "gaeul haneul yeppeunayo", "Pretty autumn sky"),
    L("난방 틀었어요", "nanbang teureosseoyo", "I turned on the heat"),
  ], ['weather']),
];
export const EXPR_WAVE3_CONCEPT_BUNDLES: VocabBundle[] = [
  concept("must-vs-should2", "Must vs should in Korean", [
    C("must", "해야 해요", "haeya haeyo", "Strict obligation icon with red stamp"),
    C("should", "하는 게 좋아요", "haneun ge joayo", "Soft advice lightbulb"),
    C("don't have to", "안 해도 돼요", "an haedo dwaeyo", "Optional chore crossed out"),
    C("mustn't", "하면 안 돼요", "hamyeon an dwaeyo", "Prohibited sign"),
  ], ['modality']),
  concept("try-vs-do", "Try vs do in Korean", [
    C("do", "해요", "haeyo", "Person completing a task"),
    C("try", "해 봐요", "hae bwayo", "Person attempting carefully"),
    C("give up", "포기해요", "pogihaeyo", "Person dropping tools"),
    C("keep trying", "계속 해 봐요", "gyesok hae bwayo", "Person retrying after failure"),
  ], ['verbs']),
  concept("give-receive2", "Give vs receive in Korean", [
    C("give", "줘요", "jwoyo", "Handing a gift"),
    C("receive", "받아요", "badayo", "Receiving a gift"),
    C("pass", "건네요", "geonneyo", "Passing an object across a table"),
    C("return", "돌려줘요", "dollyeojwoyo", "Returning a borrowed item"),
  ], ['verbs']),
  concept("come-go2", "Come vs go in Korean", [
    C("go", "가요", "gayo", "Person leaving toward a door"),
    C("come", "와요", "wayo", "Person arriving toward the viewer"),
    C("come in", "들어와요", "deureowayo", "Person entering a room"),
    C("go out", "나가요", "nagayo", "Person exiting outdoors"),
  ], ['motion']),
  concept("wear-put-on", "Wear / put on in Korean", [
    C("wear clothes", "입어요", "ibeoyo", "Putting on a jacket"),
    C("wear hat", "써요", "sseoyo", "Putting on a hat"),
    C("wear shoes", "신어요", "sineoyo", "Putting on shoes"),
    C("take off", "벗어요", "beoseoyo", "Taking off a coat"),
  ], ['daily']),
  concept("speak-say2", "Speak vs say in Korean", [
    C("say", "말해요", "malhaeyo", "Speech bubble"),
    C("speak", "이야기해요", "iyagihaeyo", "Two people chatting"),
    C("tell", "알려 줘요", "allyeo jwoyo", "Person explaining news"),
    C("ask", "물어봐요", "mureobwayo", "Person raising a hand to ask"),
  ], ['speech']),
  concept("see-look-watch2", "See / look / watch in Korean", [
    C("see", "보여요", "boyeoyo", "Eyes noticing something"),
    C("look", "봐요", "bwayo", "Person looking intently"),
    C("watch", "시청해요", "sicheonghaeyo", "Person watching TV"),
    C("stare", "쳐다봐요", "chyeodabwayo", "Intense stare"),
  ], ['verbs']),
  concept("know-think2", "Know vs think in Korean", [
    C("know", "알아요", "arayo", "Confident nod"),
    C("don't know", "몰라요", "mollayo", "Confused shrug"),
    C("think", "생각해요", "saenggakhaeyo", "Thinking pose"),
    C("guess", "추측해요", "chucheukhaeyo", "Person guessing with finger on chin"),
  ], ['cognition']),
  concept("like-love-hate", "Like love hate in Korean", [
    C("like", "좋아해요", "joahaeyo", "Warm smile toward something"),
    C("love", "사랑해요", "saranghaeyo", "Heart gesture"),
    C("dislike", "싫어해요", "sireohaeyo", "Rejecting gesture"),
    C("hate", "미워해요", "miwohaeyo", "Angry frown"),
  ], ['emotion']),
  concept("happy-sad-angry", "Basic emotions in Korean", [
    C("happy", "기뻐요", "gippeoyo", "Bright smiling face"),
    C("sad", "슬퍼요", "seulpeoyo", "Tearful face"),
    C("angry", "화나요", "hwanayo", "Steam from ears"),
    C("surprised", "놀라요", "nollayo", "Wide eyes and open mouth"),
  ], ['emotion']),
  concept("hot-cold-taste", "Hot cold taste in Korean", [
    C("hot food", "뜨거워요", "tteugeowoyo", "Steaming bowl"),
    C("cold drink", "차가워요", "chagawoyo", "Iced drink with condensation"),
    C("spicy", "매워요", "maewoyo", "Red chili and sweating face"),
    C("sweet", "달아요", "darayo", "Dessert tasting"),
  ], ['taste']),
  concept("clean-dirty", "Clean vs dirty in Korean", [
    C("clean", "깨끗해요", "kkaekkeuthaeyo", "Sparkling clean room"),
    C("dirty", "더러워요", "deoreowoyo", "Muddy shoes"),
    C("tidy", "정리됐어요", "jeongnidwaesseoyo", "Neatly organized shelf"),
    C("messy", "지저분해요", "jijeobunhaeyo", "Cluttered desk"),
  ], ['home']),
  concept("early-late2", "Early vs late in Korean", [
    C("early", "일찍", "iljjik", "Sunrise alarm"),
    C("late", "늦게", "neutge", "Person rushing after clock"),
    C("on time", "제시간에", "jesigane", "Clock hitting exact time"),
    C("delay", "지연", "jiyeon", "Delayed train board"),
  ], ['time']),
  concept("near-far2", "Near vs far in Korean", [
    C("near", "가까워요", "gakkawoyo", "Two buildings close together"),
    C("far", "멀어요", "meoreoyo", "Long road stretching away"),
    C("next to", "옆에", "yeope", "Person standing beside a friend"),
    C("across", "건너편에", "geonneopyeone", "Shop across the street"),
  ], ['location']),
  concept("before-after2", "Before vs after in Korean", [
    C("before", "전에", "jeone", "Preparation before event"),
    C("after", "후에", "hue", "Aftermath / finished plates"),
    C("during", "동안", "dongan", "Timer running mid-task"),
    C("meanwhile", "그동안", "geudongan", "Parallel clocks"),
  ], ['time']),
  concept("more-less2", "More vs less in Korean", [
    C("more", "더", "deo", "Adding another scoop"),
    C("less", "덜", "deol", "Removing some from a plate"),
    C("most", "가장", "gajang", "Tallest trophy"),
    C("least", "가장 적은", "gajang jeogeun", "Smallest portion"),
  ], ['degree']),
  concept("possible-impossible", "Possible vs impossible in Korean", [
    C("possible", "가능해요", "ganeunghaeyo", "Green check"),
    C("impossible", "불가능해요", "bulganeunghaeyo", "Red ban"),
    C("maybe", "아마", "ama", "Uncertain shrug"),
    C("definitely", "분명히", "bunmyeonghi", "Firm stamp"),
  ], ['modality']),
  concept("easy-hard2", "Easy vs hard in Korean", [
    C("easy", "쉬워요", "swiwoyo", "Simple puzzle solved"),
    C("hard", "어려워요", "eoryeowoyo", "Complex puzzle"),
    C("comfortable", "편해요", "pyeonhaeyo", "Relaxing sofa"),
    C("uncomfortable", "불편해요", "bulpyeonhaeyo", "Awkward chair"),
  ], ['evaluation']),
  concept("full-empty2", "Full vs empty in Korean", [
    C("full", "가득해요", "gadeukhaeyo", "Full glass"),
    C("empty", "비었어요", "bieosseoyo", "Empty glass"),
    C("half", "반", "ban", "Half-full glass"),
    C("overflow", "넘쳐요", "neomchyeoyo", "Overflowing cup"),
  ], ['quantity']),
  concept("begin-end2", "Begin vs end in Korean", [
    C("begin", "시작", "sijak", "Play button"),
    C("end", "끝", "kkeut", "Finish line"),
    C("pause", "일시정지", "ilsijeongji", "Pause icon"),
    C("resume", "다시 시작", "dasi sijak", "Resume arrow"),
  ], ['order']),
];
export const EXPR_WAVE3_TOPIK_BUNDLES: VocabBundle[] = [
  topik("commute-verbs", "Commute verbs: TOPIK I → II", [
    T("leave home", "나가다", "nagada", "출발하다", "chulbalhada"),
    T("arrive", "도착하다", "dochakhada", "이르다", "ireuda"),
    T("transfer", "갈아타다", "garatada", "환승하다", "hwanseunghada"),
    T("wait", "기다리다", "gidarida", "대기하다", "daegihada"),
    T("crowd", "붐비다", "bumbida", "혼잡하다", "honjaphada"),
    T("delay", "늦다", "neutda", "지연되다", "jiyeondwaeda"),
    T("board", "타다", "tada", "탑승하다", "tapseunghada"),
    T("get off", "내리다", "naerida", "하차하다", "hachahada"),
  ], ['travel']),
  topik("money-verbs2", "Money verbs: TOPIK I → II", [
    T("earn", "벌다", "beolda", "소득을 올리다", "sodeugeul ollida"),
    T("save", "모으다", "moeuda", "저축하다", "jeochukhada"),
    T("spend", "쓰다", "sseuda", "소비하다", "sobihada"),
    T("borrow", "빌리다", "billida", "대출받다", "daechulbatda"),
    T("lend", "빌려주다", "billyeojuda", "대여하다", "daeyeohada"),
    T("owe", "빚지다", "bitjida", "채무가 있다", "chaemuga itda"),
    T("invest", "투자하다", "tujahada", "운용하다", "unyonghada"),
    T("donate", "기부하다", "gibuhada", "기증하다", "gijeunghada"),
  ], ['money']),
  topik("communication2", "Communication: TOPIK I → II", [
    T("call", "전화하다", "jeonhwahada", "통화하다", "tonghwahada"),
    T("text", "문자하다", "munjahada", "메시지를 보내다", "mesijireul bonaeda"),
    T("reply", "답하다", "daphada", "회신하다", "hoesinhada"),
    T("inform", "알리다", "allida", "통보하다", "tongbohada"),
    T("explain", "설명하다", "seolmyeonghada", "해명하다", "haemyeonghada"),
    T("promise", "약속하다", "yaksokhada", "약정하다", "yakjeonghada"),
    T("apologize", "사과하다", "sagwahada", "사죄하다", "sajoehada"),
    T("thank", "감사하다", "gamsahada", "사의를 표하다", "sauireul pyohada"),
  ], ['speech']),
  topik("housing2", "Housing: TOPIK I → II", [
    T("rent", "월세", "wolse", "임대료", "imdaeryo"),
    T("deposit", "보증금", "bojeunggeum", "보증", "bojeung"),
    T("contract", "계약", "gyeyak", "약정", "yakjeong"),
    T("move in", "입주하다", "ipjuhada", "전입하다", "jeoniphada"),
    T("move out", "이사 가다", "isa gada", "퇴거하다", "toeguhada"),
    T("repair", "고치다", "gochida", "보수하다", "bosuhada"),
    T("manage", "관리하다", "gwanrihada", "운영하다", "unyonghada"),
    T("neighbor", "이웃", "iut", "인근 주민", "ingeun jumin"),
  ], ['home']),
  topik("school-life2", "School life: TOPIK I → II", [
    T("attend", "다니다", "danida", "출석하다", "chulseokhada"),
    T("skip", "빠지다", "ppajida", "결석하다", "gyeolseokhada"),
    T("graduate", "졸업하다", "joreophada", "학위를 받다", "hagwireul batda"),
    T("enroll", "입학하다", "iphakhada", "등록하다", "deungnokhada"),
    T("exam", "시험", "siheom", "평가", "pyeongga"),
    T("grade", "성적", "seongjeok", "학점", "hakjeom"),
    T("homework", "숙제", "sukje", "과제", "gwaje"),
    T("major", "전공", "jeongong", "주전공", "jujeongong"),
  ], ['school']),
  topik("environment2", "Environment: TOPIK I → II", [
    T("pollute", "더럽히다", "deoreophida", "오염시키다", "oyeomsikida"),
    T("protect", "지키다", "jikida", "보전하다", "bojeonhada"),
    T("recycle", "재활용하다", "jaehwalyonghada", "재이용하다", "jaeiyonghada"),
    T("reduce", "줄이다", "jurida", "감소시키다", "gamso sikida"),
    T("waste", "버리다", "beorida", "폐기하다", "pyegihada"),
    T("save energy", "아끼다", "akkida", "절약하다", "jeoryakhada"),
    T("plant", "심다", "simda", "식재하다", "sikjaehada"),
    T("climate", "날씨", "nalssi", "기후", "gihu"),
  ], ['environment']),
  topik("culture2", "Culture verbs: TOPIK I → II", [
    T("enjoy", "즐기다", "jeulgida", "향유하다", "hyangyuhada"),
    T("perform", "하다", "hada", "공연하다", "gongyeonhada"),
    T("exhibit", "보여 주다", "boyeo juda", "전시하다", "jeonsihada"),
    T("create", "만들다", "mandeulda", "창작하다", "changjakhada"),
    T("appreciate", "좋아하다", "joahada", "감상하다", "gamsanghada"),
    T("preserve", "지키다", "jikida", "보존하다", "bojonhada"),
    T("introduce", "소개하다", "sogaehada", "안내하다", "annahada"),
    T("celebrate", "축하하다", "chukhahada", "기념하다", "ginyeomhada"),
  ], ['culture']),
  topik("tech-verbs2", "Tech verbs: TOPIK I → II", [
    T("click", "누르다", "nureuda", "클릭하다", "keullikhada"),
    T("install", "깔다", "kkalda", "설치하다", "seolchihada"),
    T("update", "올리다", "ollida", "업데이트하다", "eopdeiteuhada"),
    T("log in", "들어가다", "deureogada", "로그인하다", "rogeinhada"),
    T("log out", "나가다", "nagada", "로그아웃하다", "rogeuautada"),
    T("backup", "복사하다", "boksahada", "백업하다", "baekeophada"),
    T("sync", "맞추다", "matchuda", "동기화하다", "donggihwahada"),
    T("encrypt", "잠그다", "jamgeuda", "암호화하다", "amhohwahada"),
  ], ['tech']),
  topik("relationship2", "Relationships: TOPIK I → II", [
    T("date", "만나다", "mannada", "연애하다", "yeonaehada"),
    T("marry", "결혼하다", "gyeolhonhada", "혼인하다", "honinhada"),
    T("divorce", "헤어지다", "heeojida", "이혼하다", "ihonhada"),
    T("introduce", "소개하다", "sogaehada", "중매하다", "jungmaehada"),
    T("break up", "차이다", "chaida", "관계를 정리하다", "gwangyereul jeongnihada"),
    T("propose", "프로포즈하다", "peuropojeuhada", "청혼하다", "cheonghonhada"),
    T("trust", "믿다", "mitda", "신뢰하다", "silloehada"),
    T("support", "도와주다", "dowajuda", "지지하다", "jijihada"),
  ], ['social']),
  topik("law-basic", "Civic verbs: TOPIK I → II", [
    T("vote", "뽑다", "ppopda", "투표하다", "tupyeohada"),
    T("rule", "규칙", "gyuchik", "법규", "beopgyu"),
    T("obey", "지키다", "jikida", "준수하다", "junsuhada"),
    T("break (rule)", "어기다", "eogida", "위반하다", "wibanhada"),
    T("report", "신고하다", "singohada", "제보하다", "jebohada"),
    T("punish", "혼내다", "honnaeda", "처벌하다", "cheobeolhada"),
    T("allow", "허락하다", "heorakhada", "허가하다", "heogahada"),
    T("forbid", "막다", "makda", "금지하다", "geumjihada"),
  ], ['civic']),
];
export const EXPR_WAVE3_SIMILAR_BUNDLES: VocabBundle[] = [
  similar("bring-take", "Bring", "Take", "가져오다", "가져가다", "gajyeooda", "gajyeogada", "bring here", "take there", "motion"),
  similar("put-on-take-off", "Put on", "Take off", "입다", "벗다", "ipda", "beotda", "put on clothes", "take off clothes", "daily"),
  similar("turn-on-off", "Turn on", "Turn off", "켜다", "끄다", "kyeoda", "kkeuda", "power on", "power off", "devices"),
  similar("enter-exit", "Enter", "Exit", "들어가다", "나가다", "deureogada", "nagada", "go in", "go out", "motion"),
  similar("rise-fall", "Rise", "Fall", "오르다", "내리다", "oreuda", "naerida", "go up", "go down", "motion"),
  similar("increase-decrease", "Increase", "Decrease", "늘다", "줄다", "neulda", "julda", "grow in amount", "shrink in amount", "quantity"),
  similar("accept-refuse", "Accept", "Refuse", "받다", "거절하다", "batda", "geojeolhada", "accept offer", "refuse offer", "social"),
  similar("allow-ban", "Allow", "Ban", "허락하다", "금지하다", "heorakhada", "geumjihada", "permit", "prohibit", "rules"),
  similar("remember-remind", "Remember", "Remind", "기억하다", "상기시키다", "gieokhada", "sanggisikida", "recall yourself", "remind someone", "cognition"),
  similar("explain-describe", "Explain", "Describe", "설명하다", "묘사하다", "seolmyeonghada", "myosahada", "explain reason", "describe appearance", "speech"),
  similar("compare-contrast", "Compare", "Contrast", "비교하다", "대조하다", "bigyohada", "dae johada", "compare similarities", "contrast differences", "cognition"),
  similar("include-exclude", "Include", "Exclude", "포함하다", "제외하다", "pohamhada", "jeoehada", "include in set", "leave out", "logic"),
  similar("connect-disconnect", "Connect", "Disconnect", "연결하다", "끊다", "yeongyeolhada", "kkeunda", "link", "cut off", "tech"),
  similar("charge-pay", "Charge", "Pay", "청구하다", "지불하다", "cheongguhada", "jibulhada", "bill someone", "pay a bill", "money"),
  similar("apply-register", "Apply", "Register", "신청하다", "등록하다", "sincheonghada", "deungnokhada", "apply for", "register officially", "admin"),
  similar("cancel-postpone", "Cancel", "Postpone", "취소하다", "미루다", "chwisohada", "miruda", "cancel entirely", "delay to later", "plans"),
  similar("approve-reject", "Approve", "Reject", "승인하다", "반려하다", "seunginhada", "banryeohada", "approve request", "send back", "admin"),
  similar("announce-notify", "Announce", "Notify", "발표하다", "통지하다", "balpyohada", "tongjihada", "public announce", "personal notify", "speech"),
  similar("collect-gather", "Collect", "Gather", "모으다", "수집하다", "moeuda", "sujiphada", "gather people/things", "collect systematically", "verbs"),
  similar("protect-defend", "Protect", "Defend", "보호하다", "방어하다", "bohohada", "bangeohada", "protect from harm", "defend against attack", "verbs"),
];

export const EXPR_WAVE3_BUNDLES: VocabBundle[] = [
  ...EXPR_WAVE3_PHRASE_BUNDLES,
  ...EXPR_WAVE3_CONCEPT_BUNDLES,
  ...EXPR_WAVE3_TOPIK_BUNDLES,
  ...EXPR_WAVE3_SIMILAR_BUNDLES,
];
