/**
 * Build deduplicated grammar comparison batch file.
 * npx tsx scripts/build-grammar-batch-1000.ts [--count 1000] [--out path]
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { isLearnerQualityComparison, LOANWORD_STEMS } from "./lib/grammar-batch-quality.ts";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");

function slugKey(words) {
  return words.map((w) => w.trim()).join("-vs-");
}

function readBatchLines(filePath: string): string[][] {
  if (!fs.existsSync(filePath)) return [];
  return fs
    .readFileSync(filePath, "utf8")
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#"))
    .map((line) =>
      line
        .split(/[,，、]/)
        .map((w) => w.trim())
        .filter(Boolean),
    )
    .filter((words) => words.length >= 2);
}

function pair(a: string, b: string): [string, string] {
  return [a, b];
}

function triple(a: string, b: string, c: string): [string, string, string] {
  return [a, b, c];
}

/** Curated + combinatorial candidate pools */
function buildCandidates(): string[][] {
  const out: string[][] = [];

  const motionPairs: Array<[string, string]> = [
    pair("가다", "오다"),
    pair("들어가다", "들어오다"),
    pair("나가다", "나오다"),
    pair("올라가다", "올라오다"),
    pair("내려가다", "내려오다"),
    pair("돌아가다", "돌아오다"),
    pair("건너가다", "건너오다"),
    pair("뛰어가다", "뛰어오다"),
    pair("달려가다", "달려오다"),
    pair("들고가다", "들고오다"),
    pair("데려가다", "데려오다"),
    pair("따라가다", "따라오다"),
    pair("보내다", "받다"),
    pair("옮기다", "가져오다"),
    pair("나눠주다", "나눠받다"),
    pair("빌려주다", "빌려받다"),
    pair("팔다", "사다"),
    pair("주다", "받다"),
    pair("가르치다", "배우다"),
    pair("일하다", "쉬다"),
    pair("깨다", "자다"),
    pair("일어나다", "눕다"),
    pair("입다", "벗다"),
    pair("켜다", "끄다"),
    pair("열다", "닫다"),
    pair("넣다", "빼다"),
    pair("붙이다", "떼다"),
    pair("올리다", "내리다"),
    pair("늘리다", "줄이다"),
    pair("늘다", "줄다"),
    pair("오르다", "내리다"),
    pair("시작하다", "끝나다"),
    pair("살다", "죽다"),
    pair("태어나다", "돌아가시다"),
    pair("만나다", "헤어지다"),
    pair("결혼하다", "이혼하다"),
    pair("취직하다", "퇴직하다"),
    pair("입학하다", "졸업하다"),
    pair("합격하다", "불합격하다"),
    pair("이기다", "지다"),
    pair("성공하다", "실패하다"),
    pair("이해하다", "오해하다"),
    pair("기억하다", "잊다"),
    pair("알다", "모르다"),
    pair("믿다", "의심하다"),
    pair("좋아하다", "싫어하다"),
    pair("원하다", "거부하다"),
    pair("동의하다", "반대하다"),
    pair("허락하다", "거절하다"),
    pair("추천하다", "비추천하다"),
    pair("칭찬하다", "비난하다"),
    pair("웃다", "울다"),
    pair("기쁘다", "슬프다"),
    pair("행복하다", "불행하다"),
    pair("편하다", "불편하다"),
    pair("쉽다", "어렵다"),
    pair("빠르다", "느리다"),
    pair("크다", "작다"),
    pair("길다", "짧다"),
    pair("높다", "낮다"),
    pair("넓다", "좁다"),
    pair("깊다", "얕다"),
    pair("무겁다", "가볍다"),
    pair("두껍다", "얇다"),
    pair("단단하다", "부드럽다"),
    pair("따뜻하다", "차갑다"),
    pair("밝다", "어둡다"),
    pair("맑다", "흐리다"),
    pair("건조하다", "습하다"),
    pair("깨끗하다", "더럽다"),
    pair("조용하다", "시끄럽다"),
    pair("바쁘다", "한가하다"),
    pair("피곤하다", "상쾌하다"),
    pair("배고프다", "부르다"),
    pair("목마르다", "배부르다"),
    pair("비싸다", "싸다"),
    pair("많다", "적다"),
    pair("충분하다", "부족하다"),
    pair("가능하다", "불가능하다"),
    pair("맞다", "틀리다"),
    pair("같다", "다르다"),
    pair("비슷하다", "다르다"),
    pair("정확하다", "부정확하다"),
    pair("명확하다", "애매하다"),
    pair("확실하다", "불확실하다"),
    pair("안전하다", "위험하다"),
    pair("건강하다", "아프다"),
    pair("재미있다", "지루하다"),
    pair("신선하다", "상하다"),
    pair("맵다", "순하다"),
    pair("짜다", "싱겁다"),
    pair("달다", "쓰다"),
    pair("뜨겁다", "차갑다"),
    pair("젖다", "마르다"),
  ];

  const particlePairs: Array<[string, string]> = [
    pair("은/는", "이/가"),
    pair("을/를", "이/가"),
    pair("에", "에서"),
    pair("에게", "한테"),
    pair("으로", "로"),
    pair("와/과", "하고"),
    pair("와/과", "랑"),
    pair("부터", "까지"),
    pair("보다", "처럼"),
    pair("만큼", "정도"),
    pair("때", "동안"),
    pair("데", "곳"),
    pair("으로부터", "에서"),
    pair("한테서", "에게서"),
    pair("보다", "보다는"),
    pair("만", "뿐"),
    pair("도", "조차"),
    pair("밖에", "만"),
    pair("마다", "씩"),
    pair("나", "이나"),
    pair("든지", "거나"),
    pair("라도", "아도"),
    pair("자", "자마자"),
    pair("면", "다면"),
    pair("는지", "은지"),
    pair("고", "면서"),
    pair("게", "도록"),
    pair("지", "죠"),
    pair("네", "구나"),
    pair("거", "것"),
    pair("듯", "같다"),
    pair("지만", "는데"),
    pair("더니", "더라"),
    pair("는데", "더니"),
    pair("고", "서"),
    pair("하려고", "려고"),
    pair("하러", "으러"),
    pair("로서", "로써"),
    pair("뿐만아니라", "뿐아니라"),
    pair("겠어", "을거야"),
    pair("ㄹ게", "을게"),
    pair("만약", "만일"),
    pair("비록", "아무리"),
    pair("어차피", "결국"),
    pair("드디어", "마침내"),
    pair("방금", "막"),
    pair("물론", "당연히"),
    pair("그런데", "근데"),
    pair("오히려", "차라리"),
    pair("대신", "대신에"),
    pair("위해서", "위한"),
    pair("통해서", "통해"),
    pair("관해서", "관해"),
    pair("대해서", "대해"),
    pair("비해서", "비해"),
    pair("왜냐하면", "때문에"),
    pair("고나서", "고나니"),
    pair("습니다", "세요"),
    pair("해요", "하세요"),
    pair("고있다", "아있다"),
    pair("해도돼", "해도돼요"),
    pair("하지마", "하지마세요"),
  ];

  const adverbPairs: Array<[string, string]> = [
    pair("매우", "상당히"),
    pair("진짜", "정말"),
    pair("약간", "살짝"),
    pair("되게", "엄청"),
    pair("곧", "머지않아"),
    pair("요즘", "최근"),
    pair("옛날", "예전"),
    pair("내일", "모레"),
    pair("어제", "그저께"),
    pair("천천히", "천히"),
    pair("빨리", "빠르게"),
    pair("잘", "제대로"),
    pair("왜", "어째서"),
    pair("어떻게", "어떡해"),
    pair("그냥", "바로"),
    pair("아마", "혹시"),
    pair("꼭", "반드시"),
    pair("거의", "대부분"),
    pair("전혀", "별로"),
    pair("조금", "잠깐"),
    pair("이미", "벌써"),
    pair("절대", "결코"),
    pair("사실", "실제로"),
    pair("자주", "종종"),
    pair("가끔", "드물게"),
    pair("먼저", "일찍"),
    pair("나중에", "후에"),
    pair("전에", "앞에"),
    pair("위", "아래"),
    pair("앞", "뒤"),
    pair("옆", "근처"),
    pair("사이", "중간"),
    pair("여기", "이곳"),
    pair("저기", "그곳"),
    pair("미안", "죄송"),
    pair("고마워", "감사"),
    pair("실례", "양해"),
    pair("알겠어", "알았어"),
    pair("그래", "응"),
    pair("네", "예"),
    pair("안녕", "안녕하세요"),
    pair("수고", "고생"),
    pair("축하해", "잘했어"),
    pair("그치", "그렇지"),
    pair("맞지", "맞죠"),
    pair("잖아", "잖아요"),
    pair("군요", "네요"),
    pair("던", "았/었던"),
  ];

  const honorificPairs: Array<[string, string]> = [
    pair("먹다", "드시다"),
    pair("자다", "주무시다"),
    pair("있다", "계시다"),
    pair("말하다", "말씀하다"),
    pair("이름", "성함"),
    pair("나이", "연세"),
    pair("집", "댁"),
    pair("밖에", "외에"),
    pair("께서", "님이"),
    pair("주다", "드리다"),
    pair("묻다", "여쭈다"),
    pair("보다", "뵙다"),
    pair("데리다", "모시다"),
    pair("죽다", "돌아가시다"),
    pair("아버지", "아버님"),
    pair("어머니", "어머님"),
    pair("할아버지", "할아버님"),
    pair("할머니", "할머님"),
    pair("선생님", "스승님"),
    pair("친구", "지인"),
  ];

  const verbStems = [
    "공부", "일", "운동", "요리", "청소", "세탁", "쇼핑", "여행", "운전", "수영",
    "등산", "낚시", "캠핑", "독서", "글쓰", "그림", "노래", "춤", "연주", "촬영",
    "편집", "업로드", "다운로드", "검색", "접속", "로그인", "결제", "환불", "예약", "취소",
    "상담", "치료", "진료", "수술", "입원", "퇴원", "검사", "측정", "기록", "보관",
    "정리", "분류", "포장", "배송", "수령", "반품", "교환", "수리", "점검", "교체",
    "설치", "해체", "조립", "분해", "연결", "분리", "결합", "혼합", "추출", "농축",
    "발명", "개발", "연구", "실험", "분석", "종합", "비교", "평가", "검토", "승인",
    "거부", "취소", "연기", "중단", "재개", "완료", "마감", "시작", "종료", "출시",
    "홍보", "광고", "판매", "구매", "임대", "대여", "양도", "상속", "증여", "기부",
    "후원", "투자", "저축", "대출", "상환", "이자", "세금", "납부", "환급", "계산",
    "협상", "계약", "해지", "연장", "갱신", "등록", "탈퇴", "가입", "초대", "추천",
    "소개", "안내", "설명", "번역", "통역", "암송", "암기", "복습", "예습", "과제",
    "제출", "채점", "합격", "불합격", "면접", "출근", "퇴근", "야근", "출장", "파견",
    "이직", "승진", "강등", "해고", "채용", "면접", "인사", "퇴사", "창업", "폐업",
    "투표", "선거", "집회", "시위", "토론", "협의", "합의", "분쟁", "중재", "판결",
    "고소", "고발", "변호", "증언", "체포", "구속", "석방", "형집행", "사면", "감형",
    "입양", "입양", "양육", "교육", "훈련", "지도", "코칭", "멘토링", "상담", "치유",
    "회복", "재활", "적응", "극복", "극복", "포기", "도전", "극복", "성취", "달성",
    "실현", "구현", "실행", "수행", "이행", "준수", "위반", "처벌", "벌금", "징역",
    "석방", "출소", "입소", "전입", "전출", "이민", "귀국", "출국", "입국", "통관",
    "검역", "검문", "심사", "승인", "거절", "입장", "퇴장", "관람", "참관", "참여",
    "불참", "참석", "주최", "후원", "개최", "폐막", "개막", "시상", "수상", "낙선",
    "당선", "낙마", "탈락", "합격", "불합격", "재시험", "면제", "유예", "연기", "조기",
  ];

  for (const stem of verbStems) {
    if (LOANWORD_STEMS.has(stem)) continue;
    motionPairs.push(pair(`${stem}하다`, `${stem}되다`));
  }

  const synonymPairs: Array<[string, string]> = [
    pair("생각하다", "생각나다"),
    pair("느끼다", "느껴지다"),
    pair("이해하다", "이해되다"),
    pair("만들다", "짓다"),
    pair("고치다", "수리하다"),
    pair("찾다", "찾아내다"),
    pair("놓다", "두다"),
    pair("가지다", "갖다"),
    pair("읽다", "읽히다"),
    pair("쓰다", "써지다"),
    pair("잃다", "잃어버리다"),
    pair("버리다", "버려지다"),
    pair("묻다", "질문하다"),
    pair("대답하다", "답하다"),
    pair("부르다", "이르다"),
    pair("살다", "지내다"),
    pair("만나다", "뵙다"),
    pair("기다리다", "참다"),
    pair("건네다", "넘기다"),
    pair("끝내다", "마치다"),
    pair("씻다", "목욕하다"),
    pair("먹다", "먹어치우다"),
    pair("요리하다", "해주다"),
    pair("청소하다", "정리하다"),
    pair("사다", "구매하다"),
    pair("팔다", "판매하다"),
    pair("빌리다", "빌려주다"),
    pair("갚다", "돌려주다"),
    pair("빌다", "부탁하다"),
    pair("약속하다", "허락하다"),
    pair("선택하다", "고르다"),
    pair("결정하다", "정하다"),
    pair("시도하다", "노력하다"),
    pair("걱정하다", "불안하다"),
    pair("화나다", "짜증나다"),
    pair("피곤하다", "졸리다"),
    pair("아프다", "다치다"),
    pair("놀다", "즐기다"),
    pair("근무하다", "일하다"),
    pair("휴식하다", "쉬다"),
    pair("복습하다", "공부하다"),
    pair("외우다", "암기하다"),
    pair("그리다", "그려지다"),
    pair("웃음나다", "웃다"),
    pair("눈물나다", "울다"),
    pair("소리치다", "외치다"),
    pair("꿈꾸다", "상상하다"),
    pair("포기하다", "그만두다"),
    pair("계속하다", "이어가다"),
    pair("멈추다", "서다"),
    pair("숨기다", "감추다"),
    pair("드러내다", "밝히다"),
    pair("사과하다", "용서하다"),
    pair("싸우다", "다투다"),
    pair("격려하다", "칭찬하다"),
    pair("참석하다", "출석하다"),
    pair("초대하다", "불러주다"),
    pair("방문하다", "찾아가다"),
    pair("연락하다", "전화하다"),
    pair("전달하다", "전해주다"),
    pair("지불하다", "계산하다"),
    pair("예약하다", "예매하다"),
    pair("환불받다", "취소하다"),
    pair("교환하다", "바꾸다"),
    pair("고장나다", "멈추다"),
    pair("닦다", "문지르다"),
    pair("빨래하다", "세탁하다"),
    pair("말리다", "건조시키다"),
    pair("굽다", "데우다"),
    pair("식다", "식히다"),
    pair("끓이다", "삶다"),
    pair("섞다", "비빈다"),
    pair("썰다", "다지다"),
    pair("볶다", "튀기다"),
    pair("익다", "익히다"),
    pair("굵다", "가늘다"),
    pair("희망하다", "기대하다"),
    pair("놀라다", "깜짝놀라다"),
    pair("부끄럽다", "창피하다"),
    pair("쑥스럽다", "민망하다"),
    pair("자신있다", "자신없다"),
    pair("부럽다", "질투하다"),
    pair("외롭다", "쓸쓸하다"),
    pair("긴장하다", "떨리다"),
    pair("간단하다", "복잡하다"),
    pair("깔끔하다", "지저분하다"),
    pair("시원하다", "답답하다"),
    pair("춥다", "쌀쌀하다"),
    pair("올바르다", "잘못되다"),
    pair("받다", "받아지다"),
    pair("주다", "줘지다"),
    pair("걷다", "걸어가다"),
    pair("뛰다", "달리다"),
    pair("앉다", "앉아있다"),
    pair("서다", "서있다"),
    pair("일어나다", "기상하다"),
    pair("입다", "걸치다"),
    pair("벗다", "벗어내다"),
    pair("요리하다", "만들다"),
    pair("빌리다", "빌려주다"),
    pair("갚다", "상환하다"),
    pair("모으다", "저축하다"),
    pair("쓰다", "소비하다"),
    pair("절약하다", "아끼다"),
    pair("배우다", "익히다"),
    pair("가르치다", "교육하다"),
    pair("공부하다", "학습하다"),
    pair("시험보다", "응시하다"),
    pair("졸업하다", "수료하다"),
    pair("입학하다", "전학하다"),
    pair("취직하다", "구직하다"),
    pair("퇴직하다", "사직하다"),
    pair("출근하다", "퇴근하다"),
    pair("야근하다", "초과근무하다"),
    pair("휴가", "연차"),
    pair("병원", "의원"),
    pair("약", "한약"),
    pair("아프다", "편찮다"),
    pair("낫다", "회복하다"),
    pair("태어나다", "출생하다"),
    pair("결혼하다", "혼인하다"),
    pair("이혼하다", "별거하다"),
    pair("이사하다", "전입하다"),
    pair("여행하다", "관광하다"),
    pair("출발하다", "도착하다"),
    pair("탑승하다", "하차하다"),
    pair("예약하다", "취소하다"),
    pair("환불하다", "교환하다"),
    pair("배송하다", "택배"),
    pair("포장하다", "봉투에넣다"),
    pair("선물하다", "증정하다"),
    pair("축하하다", "축하드리다"),
    pair("위로하다", "격려하다"),
    pair("사과하다", "사과드리다"),
    pair("감사하다", "감사드리다"),
    pair("실례하다", "실례합니다"),
    pair("허락하다", "허락받다"),
    pair("거절하다", "거부하다"),
    pair("동의하다", "찬성하다"),
    pair("반대하다", "이의하다"),
    pair("제안하다", "권하다"),
    pair("추천하다", "소개하다"),
    pair("비교하다", "대조하다"),
    pair("분석하다", "해석하다"),
    pair("정리하다", "정돈하다"),
    pair("청소하다", "치우다"),
    pair("닦다", "닦아내다"),
    pair("다림질하다", "다리다"),
    pair("버리다", "폐기하다"),
    pair("재활용하다", "분리수거하다"),
  ];

  const similarTriples: Array<[string, string, string]> = [
    triple("그래서", "그러니까", "그러면"),
    triple("먼저", "일단", "우선"),
    triple("조금", "약간", "살짝"),
    triple("정말", "진짜", "참"),
    triple("같이", "함께", "서로"),
    triple("와", "과", "하고"),
    triple("에", "에서", "에게"),
    triple("도", "까지", "조차"),
    triple("아니면", "혹은", "또는"),
    triple("그래도", "그럼에도", "하지만"),
    triple("위해서", "위해", "때문에"),
    triple("전에", "앞에", "이전에"),
    triple("후에", "다음에", "이후에"),
    triple("만", "뿐", "뿐만"),
    triple("처럼", "같이", "만큼"),
    triple("때", "동안", "사이"),
    triple("싶다", "원하다", "바라다"),
    triple("계속", "줄곧", "꾸준히"),
    triple("자주", "가끔", "때때로"),
    triple("빨리", "서둘러", "급히"),
    triple("으로", "로", "에"),
    triple("부터", "에서부터", "부터는"),
    triple("마저", "조차", "까지"),
    triple("이나", "나", "이나마"),
    triple("든지", "든", "든가"),
    triple("라도", "이나", "이든"),
    triple("겠", "을게", "을거야"),
    triple("던", "았던", "었던"),
    triple("해서", "하니까", "하여"),
    triple("뿐", "뿐만", "뿐이다"),
    triple("하지만", "그런데", "그렇지만"),
    triple("이렇게", "저렇게", "그렇게"),
    triple("아직", "벌써", "이제"),
    triple("많이", "너무", "아주"),
    triple("항상", "맨날", "자주"),
    triple("에게", "한테", "께"),
    triple("여기", "저기", "거기"),
    triple("이", "그", "저"),
    triple("아서", "어서", "니까"),
    triple("오늘", "어제", "내일"),
    triple("아침", "점심", "저녁"),
    triple("월요일", "화요일", "수요일"),
    triple("봄", "여름", "가을"),
    triple("초반", "중반", "후반"),
    triple("위", "아래", "옆"),
    triple("앞", "뒤", "옆"),
    triple("시작", "중간", "끝"),
    triple("원인", "과정", "결과"),
    triple("과거", "현재", "미래"),
    triple("가능", "불가능", "어려움"),
    triple("좋음", "보통", "나쁨"),
    triple("크게", "조금", "살짝"),
    triple("항상", "가끔", "절대"),
    triple("빨리", "천천히", "제때"),
    triple("쉽게", "어렵게", "힘들게"),
    triple("밖에서", "안에서", "근처에서"),
    triple("혼자", "둘이서", "함께"),
    triple("직접", "간접", "대리"),
    triple("공식", "비공식", "반말"),
    triple("문어", "구어", "속어"),
    triple("겠습니다", "을게요", "을 거예요"),
    triple("세요", "십시오", "하세요"),
    triple("네요", "군요", "구나"),
    triple("잖아", "잖아요", "거든"),
    triple("는데", "은데", "건데"),
    triple("다면", "면", "거라면"),
    triple("더니", "고 나서", "자마자"),
    triple("도록", "게", "라고"),
    triple("밖에", "만", "뿐"),
    triple("조차", "마저", "까지"),
    triple("이라도", "라도", "이나"),
    triple("하든지", "든지", "거나"),
    triple("아도", "어도", "여도"),
    triple("거든", "니까", "어서"),
    triple("는지", "은지", "인지"),
    triple("다가", "다가는", "자마자"),
    triple("면서", "으며", "고"),
    triple("려고", "러", "고 싶어서"),
    triple("마다", "씩", "마다마다"),
    triple("처럼", "같이", "듯이"),
    triple("보다", "만큼", "정도"),
    triple("때", "무렵", "즈음"),
    triple("동안", "사이", "가운데"),
    triple("안", "속", "내부"),
    triple("밖", "외부", "밖쪽"),
    triple("옆", "곁", "이웃"),
    triple("근처", "부근", "주변"),
    triple("위에", "위", "위쪽"),
    triple("아래", "밑", "하단"),
    triple("앞쪽", "앞", "전방"),
    triple("뒤쪽", "뒤", "후방"),
    triple("아까", "방금", "조금 전"),
    triple("이따", "나중에", "후에"),
    triple("곧", "머지않아", "이내"),
    triple("벌써", "이미", "벌써부터"),
    triple("아직", "여전히", "계속"),
    triple("다시", "또", "재차"),
    triple("오히려", "차라리", "도리어"),
    triple("그냥", "그저", "단지"),
    triple("정말", "정말로", "참으로"),
    triple("진짜", "정말", "너무"),
    triple("매우", "아주", "무척"),
    triple("조금", "약간", "살짝"),
    triple("거의", "대체로", "웬만큼"),
    triple("전혀", "별로", "조금도"),
    triple("꼭", "반드시", "틀림없이"),
    triple("아마", "혹시", "어쩌면"),
    triple("분명", "확실히", "틀림없이"),
    triple("갑자기", "문득", "불씨"),
    triple("천천히", "느리게", "서서히"),
    triple("빨리", "서둘러", "급히"),
    triple("함께", "같이", "더불어"),
    triple("서로", "맞서", "서로서로"),
    triple("혼자", "홀로", "단독"),
    triple("직접", "손수", "몸소"),
    triple("간접", "우회", "돌려"),
    triple("공식", "격식", "정식"),
    triple("비공식", "캐주얼", "편하게"),
    triple("문어", "글", "책말"),
    triple("구어", "말", "대화"),
    triple("존댓말", "높임말", "경어"),
    triple("반말", "낮춤말", "편말"),
    triple("표준어", "표준", "본말"),
    triple("방언", "사투리", "지역어"),
    triple("한자어", "한자", "한자말"),
    triple("고유어", "순우리말", "우리말"),
    triple("외래어", "외국어", "차용어"),
    triple("유행어", "신조어", "줄임말"),
    triple("속어", "비속어", "은어"),
    triple("격식체", "문어체", "공문체"),
    triple("구어체", "대화체", "일상체"),
    triple("하오체", "하게체", "해라체"),
    triple("해요체", "합니다체", "해체"),
    triple("명령", "청유", "감탄"),
    triple("평서", "의문", "감탄문"),
    triple("긍정", "부정", "의문"),
    triple("능동", "수동", "피동"),
    triple("사동", "피동", "사역"),
    triple("현재", "과거", "미래"),
    triple("진행", "완료", "경험"),
    triple("추측", "회상", "전망"),
    triple("연결", "종결", "전성"),
    triple("주격", "목적격", "보격"),
    triple("격조사", "보조사", "접속조사"),
    triple("의존명사", "단위명사", "대명사"),
    triple("자동사", "타동사", "준타동사"),
    triple("규칙활용", "불규칙활용", "예외활용"),
    triple("높임", "낮춤", "중립"),
    triple("강조", "완화", "생략"),
    triple("직설", "완곡", "돌려말하기"),
    triple("의역", "직역", "자연스러운 번역"),
  ];

  const _deprecatedGenericTriples: Array<[string, string, string]> = [
    triple("한국어", "영어", "중국어"),
    triple("남자", "여자", "아이"),
    triple("학생", "직장인", "주부"),
    triple("도시", "시골", "해외"),
    triple("집", "회사", "학교"),
    triple("전화", "문자", "카톡"),
    triple("현금", "카드", "계좌이체"),
    triple("버스", "지하철", "택시"),
    triple("밥", "국", "반찬"),
    triple("커피", "차", "물"),
    triple("책", "영화", "드라마"),
    triple("운동", "공부", "취미"),
    triple("계획", "실행", "점검"),
    triple("질문", "답변", "설명"),
    triple("제안", "협의", "결정"),
    triple("신청", "심사", "승인"),
    triple("준비", "진행", "마무리"),
    triple("입력", "수정", "삭제"),
    triple("업로드", "다운로드", "공유"),
    triple("로그인", "로그아웃", "회원가입"),
    triple("검색", "필터", "정렬"),
    triple("알림", "메시지", "공지"),
    triple("할인", "적립", "환불"),
    triple("배송", "수령", "반품"),
    triple("예약", "변경", "취소"),
    triple("출발", "경유", "도착"),
    triple("체크인", "체크아웃", "연장"),
    triple("면접", "합격", "입사"),
    triple("퇴사", "이직", "창업"),
    triple("수업", "숙제", "시험"),
    triple("강의", "토론", "발표"),
    triple("읽기", "쓰기", "말하기"),
    triple("듣기", "따라하기", "반복하기"),
    triple("문법", "어휘", "발음"),
    triple("격식", "반격식", "친근함"),
    triple("긍정", "부정", "중립"),
    triple("사실", "의견", "추측"),
    triple("원인", "이유", "목적"),
    triple("방법", "수단", "도구"),
    triple("문제", "해결", "예방"),
    triple("장점", "단점", "특징"),
    triple("비슷함", "차이", "대조"),
    triple("기본", "응용", "심화"),
    triple("입문", "중급", "고급"),
    triple("일상", "비즈니스", "학술"),
    triple("구어체", "문어체", "격식체"),
    triple("존댓말", "반말", "하오체"),
    triple("남성어", "여성어", "중립어"),
    triple("표준어", "방언", "신조어"),
    triple("한자어", "고유어", "외래어"),
    triple("단어", "구", "문장"),
    triple("주어", "목적어", "보어"),
    triple("형용사", "부사", "조사"),
    triple("현재", "과거", "미래"),
    triple("능동", "수동", "사역"),
    triple("진행", "완료", "경험"),
    triple("추측", "확정", "부정"),
    triple("명령", "청유", "감탄"),
    triple("연결", "종결", "전달"),
    triple("높임", "낮춤", "중립"),
    triple("강조", "완화", "생략"),
    triple("긍정문", "부정문", "의문문"),
    triple("평서", "의문", "감탄"),
    triple("직설", "완곡", "은유"),
    triple("공손", "친근", "무례"),
    triple("격식", "캐주얼", "속어"),
    triple("문장", "절", "구"),
    triple("연결어미", "종결어미", "전성어미"),
    triple("시제", "상", "태"),
    triple("주격", "목적격", "부사격"),
    triple("보조사", "격조사", "접속조사"),
    triple("의존명사", "독립명사", "대명사"),
    triple("자동사", "타동사", "사동사"),
    triple("규칙", "불규칙", "예외"),
    triple("표준", "비표준", "구어"),
    triple("문법", "어휘", "표현"),
    triple("의미", "뉘앙스", "용법"),
    triple("맥락", "상황", "의도"),
    triple("화자", "청자", "상대"),
    triple("격식", "비격식", "반말"),
    triple("직역", "의역", "자연스러움"),
    triple("문장", "대화", "독백"),
    triple("설명", "예시", "연습"),
    triple("오류", "교정", "개선"),
    triple("습관", "실수", "팁"),
    triple("기초", "중급", "실전"),
    triple("이론", "연습", "응용"),
    triple("읽기", "듣기", "쓰기"),
    triple("말하기", "토론", "발표"),
    triple("단답", "서술", "토론"),
    triple("암기", "이해", "응용"),
    triple("반복", "변형", "확장"),
    triple("교재", "강의", "실습"),
    triple("시험", "과제", "프로젝트"),
    triple("피드백", "수정", "완성"),
    triple("목표", "계획", "성과"),
    triple("동기", "습관", "성취"),
    triple("어려움", "극복", "성장"),
    triple("실수", "교정", "습득"),
    triple("질문", "답", "추가질문"),
    triple("예문", "반례", "연습"),
    triple("규칙", "예외", "팁"),
    triple("의미", "쓰임", "뉘앙스"),
    triple("격식", "일상", "속담"),
    triple("문어", "구어", "대화"),
    triple("한국", "미국", "일본"),
    triple("서울", "부산", "제주"),
    triple("한식", "양식", "중식"),
    triple("김치", "된장", "고추장"),
    triple("노래", "춤", "연기"),
    triple("드라마", "영화", "예능"),
    triple("뉴스", "기사", "칼럼"),
    triple("소설", "시", "수필"),
    triple("이메일", "보고서", "제안서"),
    triple("회의", "발표", "협상"),
    triple("면접", "프레젠테이션", "네트워킹"),
    triple("이력서", "자기소개", "추천서"),
    triple("연봉", "복지", "성과급"),
    triple("출근", "재택", "출장"),
    triple("야근", "휴가", "병가"),
    triple("상사", "동료", "부하"),
    triple("고객", "파트너", "경쟁사"),
    triple("마케팅", "영업", "고객지원"),
    triple("기획", "개발", "운영"),
    triple("디자인", "개발", "테스트"),
    triple("버그", "패치", "업데이트"),
    triple("데이터", "분석", "시각화"),
    triple("보안", "개인정보", "규정"),
    triple("계약", "조건", "서명"),
    triple("견적", "발주", "납품"),
    triple("재고", "주문", "배송"),
    triple("매출", "비용", "이익"),
    triple("투자", "수익", "리스크"),
    triple("성장", "정체", "하락"),
    triple("혁신", "개선", "유지"),
    triple("목표", "전략", "실행"),
    triple("팀", "개인", "조직"),
    triple("리더", "멤버", "멘토"),
    triple("목표", "우선순위", "마감"),
    triple("아이디어", "실행", "검증"),
    triple("성공", "실패", "배움"),
    triple("시작", "지속", "완료"),
    triple("문제", "원인", "해결"),
    triple("계획", "변수", "대안"),
    triple("협업", "소통", "갈등"),
    triple("피드백", "수용", "개선"),
    triple("목표", "진척", "결과"),
    triple("습관", "루틴", "시스템"),
    triple("동기", "집중", "완성"),
    triple("학습", "복습", "적용"),
    triple("이해", "기억", "표현"),
    triple("듣기", "말하기", "읽기"),
    triple("문법", "발음", "억양"),
    triple("어휘", "표현", "관용구"),
    triple("격식", "반말", "존댓말"),
    triple("문장", "대화", "글"),
    triple("설명", "질문", "답변"),
    triple("예문", "퀴즈", "복습"),
    triple("기초", "응용", "마스터"),
    triple("실수", "교정", "자연스러움"),
    triple("의미", "용법", "뉘앙스"),
    triple("맥락", "상황", "의도"),
    triple("화자", "청자", "관계"),
    triple("목적", "방법", "결과"),
    triple("원인", "과정", "결론"),
    triple("비교", "대조", "구분"),
    triple("유사", "차이", "선택"),
    triple("긍정", "부정", "중립"),
    triple("강조", "완화", "생략"),
    triple("직설", "완곡", "은유"),
    triple("공손", "친근", "격식"),
    triple("문어", "구어", "대화체"),
    triple("표준", "방언", "신어"),
    triple("한자어", "고유어", "외래어"),
    triple("단어", "구", "절"),
    triple("문장", "문단", "글"),
    triple("읽기", "쓰기", "말하기"),
    triple("이해", "표현", "소통"),
    triple("학습", "연습", "실전"),
    triple("기초", "중급", "고급"),
    triple("문법", "어휘", "발음"),
    triple("시험", "회화", "작문"),
    triple("암기", "이해", "응용"),
    triple("반복", "변형", "확장"),
    triple("교재", "강의", "실습"),
    triple("목표", "계획", "성과"),
    triple("동기", "습관", "성취"),
    triple("어려움", "극복", "성장"),
    triple("실수", "교정", "습득"),
    triple("질문", "답", "추가질문"),
    triple("예문", "반례", "연습"),
    triple("규칙", "예외", "팁"),
  ];
  void _deprecatedGenericTriples;

  for (const p of motionPairs) out.push([...p]);
  for (const p of particlePairs) out.push([...p]);
  for (const p of adverbPairs) out.push([...p]);
  for (const p of honorificPairs) out.push([...p]);
  for (const p of synonymPairs) out.push([...p]);
  for (const t of similarTriples) out.push([...t]);

  const extraPairs: Array<[string, string]> = [
    pair("학교", "학원"),
    pair("병원", "약국"),
    pair("은행", "ATM"),
    pair("마트", "편의점"),
    pair("카페", "식당"),
    pair("호텔", "모텔"),
    pair("비행기", "기차"),
    pair("버스", "택시"),
    pair("지하철", "KTX"),
    pair("자전거", "오토바이"),
    pair("운전면허", "여권"),
    pair("신분증", "학생증"),
    pair("계약서", "영수증"),
    pair("이력서", "자기소개서"),
    pair("면접", "시험"),
    pair("과제", "숙제"),
    pair("강의", "세미나"),
    pair("교과서", "참고서"),
    pair("필기", "실기"),
    pair("중간고사", "기말고사"),
    pair("수능", "모의고사"),
    pair("장학금", "대출"),
    pair("등록금", "학비"),
    pair("월세", "전세"),
    pair("보증금", "계약금"),
    pair("월급", "보너스"),
    pair("연봉", "시급"),
    pair("세금", "공과금"),
    pair("보험", "적금"),
    pair("주식", "채권"),
    pair("코인", "현금"),
    pair("신용카드", "체크카드"),
    pair("송금", "이체"),
    pair("출금", "입금"),
    pair("잔액", "한도"),
    pair("비밀번호", "인증번호"),
    pair("로그인", "회원가입"),
    pair("앱", "웹"),
    pair("업데이트", "설치"),
    pair("삭제", "복구"),
    pair("백업", "동기화"),
    pair("알림", "푸시"),
    pair("댓글", "좋아요"),
    pair("구독", "팔로우"),
    pair("라이브", "녹화"),
    pair("촬영", "편집"),
    pair("업로드", "다운로드"),
    pair("공유", "저장"),
    pair("검색", "추천"),
    pair("필터", "정렬"),
    pair("리뷰", "평점"),
    pair("배송", "픽업"),
    pair("무료배송", "당일배송"),
    pair("교환", "반품"),
    pair("AS", "수리"),
    pair("보증", "환불"),
    pair("쿠폰", "할인"),
    pair("포인트", "마일리지"),
    pair("멤버십", "구독"),
    pair("예약", "대기"),
    pair("입장", "퇴장"),
    pair("체크인", "체크아웃"),
    pair("조식", "석식"),
    pair("단품", "세트"),
    pair("사이즈", "색상"),
    pair("재고", "품절"),
    pair("신상", "할인상품"),
    pair("국내", "해외"),
    pair("직구", "면세"),
    pair("통관", "관세"),
    pair("영수증", "계산서"),
    pair("현금영수증", "세금계산서"),
    pair("개인", "법인"),
    pair("대표", "담당자"),
    pair("팀장", "사원"),
    pair("인턴", "정규직"),
    pair("프리랜서", "계약직"),
    pair("재택", "출근"),
    pair("회의", "미팅"),
    pair("보고", "공유"),
    pair("기한", "마감"),
    pair("우선순위", "일정"),
    pair("목표", "KPI"),
    pair("성과", "평가"),
    pair("피드백", "코칭"),
    pair("온보딩", "오프보딩"),
    pair("퇴사", "이직"),
    pair("승진", "전보"),
    pair("부서", "팀"),
    pair("본사", "지사"),
    pair("고객", "클라이언트"),
    pair("제안", "견적"),
    pair("계약", "납품"),
    pair("매출", "수익"),
    pair("비용", "지출"),
    pair("이익", "손실"),
    pair("투자", "회수"),
    pair("마케팅", "브랜딩"),
    pair("광고", "홍보"),
    pair("캠페인", "이벤트"),
    pair("랜딩페이지", "배너"),
    pair("전환", "유입"),
    pair("리텐션", "이탈"),
    pair("데이터", "인사이트"),
    pair("지표", "대시보드"),
    pair("버그", "오류"),
    pair("패치", "핫픽스"),
    pair("배포", "롤백"),
    pair("테스트", "검증"),
    pair("기획", "디자인"),
    pair("프론트", "백엔드"),
    pair("API", "DB"),
    pair("서버", "클라이언트"),
    pair("보안", "권한"),
    pair("암호", "토큰"),
    pair("백업", "복구"),
    pair("모니터링", "알람"),
    pair("장애", "복구"),
    pair("요청", "응답"),
    pair("입력", "출력"),
    pair("저장", "불러오기"),
    pair("생성", "삭제"),
    pair("수정", "조회"),
    pair("등록", "해제"),
    pair("승인", "반려"),
    pair("접수", "완료"),
    pair("대기", "처리중"),
    pair("보류", "종료"),
    pair("재시도", "취소"),
    pair("연장", "만료"),
    pair("갱신", "해지"),
    pair("변경", "유지"),
    pair("추가", "제거"),
    pair("확대", "축소"),
    pair("활성", "비활성"),
    pair("공개", "비공개"),
    pair("임시", "영구"),
    pair("초안", "최종"),
    pair("검토", "확정"),
    pair("배포", "배포완료"),
    pair("오픈", "클로즈"),
    pair("시작", "종료"),
    pair("진행", "완료"),
    pair("성공", "실패"),
    pair("정상", "오류"),
    pair("가능", "불가"),
    pair("허용", "차단"),
    pair("필수", "선택"),
    pair("기본", "고급"),
    pair("간단", "상세"),
    pair("요약", "전체"),
    pair("목록", "상세"),
    pair("검색", "필터"),
    pair("정렬", "그룹"),
    pair("오름차순", "내림차순"),
    pair("최신", "인기"),
    pair("추천", "랜덤"),
    pair("즐겨찾기", "최근"),
    pair("알림", "음소거"),
    pair("팔로우", "차단"),
    pair("신고", "문의"),
    pair("도움말", "FAQ"),
    pair("가이드", "튜토리얼"),
    pair("설정", "프로필"),
    pair("언어", "테마"),
    pair("다크모드", "라이트모드"),
    pair("알림", "방해금지"),
    pair("위치", "권한"),
    pair("카메라", "마이크"),
    pair("연락처", "갤러리"),
    pair("파일", "폴더"),
    pair("문서", "이미지"),
    pair("PDF", "이미지"),
    pair("링크", "첨부"),
    pair("제목", "내용"),
    pair("본문", "댓글"),
    pair("태그", "카테고리"),
    pair("버전", "업데이트"),
    pair("릴리즈", "베타"),
    pair("정식", "시범"),
    pair("무료", "유료"),
    pair("체험", "구독"),
    pair("월간", "연간"),
    pair("할인", "정가"),
    pair("쿠폰", "프로모션"),
    pair("이벤트", "기획전"),
    pair("선착순", "한정"),
    pair("재입고", "품절"),
    pair("예약판매", "즉시구매"),
    pair("현장", "온라인"),
    pair("대면", "비대면"),
    pair("오프라인", "온라인"),
    pair("실시간", "녹화"),
    pair("라이브", "VOD"),
    pair("스트리밍", "다운로드"),
    pair("화질", "음질"),
    pair("자막", "더빙"),
    pair("원어", "번역"),
    pair("한국어", "영어자막"),
    pair("더빙", "자막"),
    pair("시즌", "에피소드"),
    pair("예고편", "본편"),
    pair("스포일러", "리뷰"),
    pair("추천", "비추천"),
    pair("명대사", "대사"),
    pair("OST", "BGM"),
    pair("배우", "감독"),
    pair("주연", "조연"),
    pair("로맨스", "스릴러"),
    pair("코미디", "드라마"),
    pair("다큐", "예능"),
    pair("뉴스", "시사"),
    pair("칼럼", "기사"),
    pair("속보", "단신"),
    pair("제보", "인터뷰"),
    pair("기자", "앵커"),
    pair("방송", "출연"),
    pair("MC", "게스트"),
    pair("팬", "안티"),
    pair("응원", "비판"),
    pair("화제", "논란"),
    pair("인기", "화제성"),
    pair("트렌드", "밈"),
    pair("챌린지", "유행어"),
    pair("신조어", "줄임말"),
    pair("은어", "속어"),
    pair("비속어", "욕설"),
    pair("농담", "진담"),
    pair("반말", "존댓말"),
    pair("경어", "반말"),
    pair("하오체", "해요체"),
    pair("합니다체", "해요체"),
    pair("합쇼체", "하십시오체"),
    pair("하게체", "해라체"),
    pair("해라체", "해체"),
    pair("시제", "서법"),
    pair("높임법", "격식체"),
    pair("주격조사", "보조사"),
    pair("목적격", "부사격"),
    pair("관형격", "보어격"),
    pair("연결어미", "종결어미"),
    pair("관형사형", "종결형"),
    pair("평서형", "의문형"),
    pair("명령형", "청유형"),
    pair("감탄형", "평서형"),
    pair("현재형", "과거형"),
    pair("미래", "추측"),
    pair("진행", "완료"),
    pair("수동", "사동"),
    pair("피동", "사동"),
    pair("가능", "의무"),
    pair("추측", "회상"),
    pair("경험", "완료"),
    pair("계속", "결과"),
    pair("시작", "중단"),
    pair("이유", "원인"),
    pair("목적", "결과"),
    pair("조건", "가정"),
    pair("양보", "대조"),
    pair("나열", "선택"),
    pair("인용", "전달"),
    pair("부사절", "명사절"),
    pair("관형절", "부사절"),
    pair("안", "못"),
    pair("잘", "못"),
    pair("더", "덜"),
    pair("매우", "조금"),
    pair("너무", "충분히"),
    pair("거의", "전혀"),
    pair("항상", "가끔"),
    pair("자주", "드물게"),
    pair("곧", "나중에"),
    pair("벌써", "아직"),
    pair("이미", "이제"),
    pair("방금", "조금전"),
    pair("오늘", "내일"),
    pair("어제", "모레"),
    pair("이번주", "다음주"),
    pair("지난달", "이번달"),
    pair("작년", "올해"),
    pair("내년", "올해"),
    pair("아침", "저녁"),
    pair("새벽", "밤"),
    pair("평일", "주말"),
    pair("휴일", "근무일"),
    pair("봄", "가을"),
    pair("여름", "겨울"),
    pair("초여름", "한여름"),
    pair("초겨울", "한겨울"),
    pair("맑음", "흐림"),
    pair("비", "눈"),
    pair("소나기", "장마"),
    pair("더위", "추위"),
    pair("습도", "건조"),
    pair("미세먼지", "황사"),
    pair("태풍", "폭우"),
    pair("지진", "해일"),
    pair("화재", "침수"),
    pair("사고", "사건"),
    pair("응급", "응급실"),
    pair("구급차", "119"),
    pair("경찰", "소방"),
    pair("신고", "출동"),
    pair("벌금", "과태료"),
    pair("면허", "등록"),
    pair("위반", "준수"),
    pair("신호", "표지판"),
    pair("횡단보도", "육교"),
    pair("주차", "정차"),
    pair("속도", "거리"),
    pair("출발", "정차"),
    pair("우회", "직진"),
    pair("유턴", "깜빡이"),
    pair("안전벨트", "에어백"),
    pair("운전", "조수"),
    pair("내비", "지도"),
    pair("GPS", "나침반"),
    pair("목적지", "경유지"),
    pair("도보", "대중교통"),
    pair("환승", "하차"),
    pair("막차", "첫차"),
    pair("종점", "기점"),
    pair("승차권", "정기권"),
    pair("교통카드", "현금"),
    pair("좌석", "입석"),
    pair("예매", "현장구매"),
    pair("왕복", "편도"),
    pair("직항", "경유"),
    pair("출국", "입국"),
    pair("면세", "유학"),
    pair("비자", "여권"),
    pair("환전", "송금"),
    pair("짐", "수하물"),
    pair("캐리어", "백팩"),
    pair("숙소", "게스트하우스"),
    pair("호스텔", "리조트"),
    pair("체크아웃", "레이트"),
    pair("조식", "룸서비스"),
    pair("관광", "쇼핑"),
    pair("기념품", "면세품"),
    pair("맛집", "카페"),
    pair("예약", "워크인"),
    pair("대기", "바로입장"),
    pair("포장", "매장"),
    pair("배달", "픽업"),
    pair("쿠팡", "배민"),
    pair("리뷰", "별점"),
    pair("메뉴", "세트"),
    pair("사이드", "메인"),
    pair("디저트", "음료"),
    pair("아메리카노", "라떼"),
    pair("HOT", "ICE"),
    pair("샷추가", "시럽"),
    pair("매운맛", "순한맛"),
    pair("곱배기", "일반"),
    pair("반찬", "밥"),
    pair("국", "찌개"),
    pair("탕", "전골"),
    pair("구이", "찜"),
    pair("볶음", "튀김"),
    pair("김치", "나물"),
    pair("밥", "면"),
    pair("떡", "빵"),
    pair("과일", "채소"),
    pair("고기", "생선"),
    pair("돼지", "소"),
    pair("닭", "오리"),
    pair("채식", "육식"),
    pair("알레르기", "비건"),
    pair("유통기한", "소비기한"),
    pair("냉장", "냉동"),
    pair("해동", "조리"),
    pair("굽기", "삶기"),
    pair("간", "싱겁게"),
    pair("매콤", "달콤"),
    pair("고소", "담백"),
    pair("식사", "간식"),
    pair("아침식사", "브런치"),
    pair("점심", "도시락"),
    pair("야식", "간단히"),
    pair("회식", "미팅"),
    pair("술", "안주"),
    pair("소주", "맥주"),
    pair("막걸리", "와인"),
    pair("건배", "축배"),
    pair("안주", "메인"),
    pair("첫잔", "마지막잔"),
    pair("만취", "적당히"),
    pair("해장", "커피"),
    pair("다이어트", "운동"),
    pair("헬스", "요가"),
    pair("런닝", "걷기"),
    pair("스트레칭", "마사지"),
    pair("근력", "유산소"),
    pair("체중", "체지방"),
    pair("키", "몸무게"),
    pair("혈압", "혈당"),
    pair("수면", "낮잠"),
    pair("불면", "피로"),
    pair("스트레스", "휴식"),
    pair("명상", "호흡"),
    pair("취미", "특기"),
    pair("독서", "영화감상"),
    pair("게임", "운동"),
    pair("여행", "캠핑"),
    pair("사진", "영상"),
    pair("그림", "음악"),
    pair("악기", "노래"),
    pair("콘서트", "뮤지컬"),
    pair("전시", "공연"),
    pair("박물관", "미술관"),
    pair("도서관", "서점"),
    pair("공원", "산책"),
    pair("등산", "낚시"),
    pair("수영", "서핑"),
    pair("스키", "보드"),
    pair("골프", "테니스"),
    pair("축구", "야구"),
    pair("농구", "배구"),
    pair("배드민턴", "탁구"),
    pair("볼링", "당구"),
    pair("e스포츠", "보드게임"),
    pair("퍼즐", "퀴즈"),
    pair("스도쿠", "크로스워드"),
    pair("반려동물", "반려식물"),
    pair("강아지", "고양이"),
    pair("산책", "목욕"),
    pair("사료", "간식"),
    pair("병원", "미용"),
    pair("예방접종", "건강검진"),
    pair("이발", "파마"),
    pair("염색", "펌"),
    pair("네일", "피부관리"),
    pair("화장", "스킨케어"),
    pair("선크림", "보습"),
    pair("향수", "로션"),
    pair("옷", "신발"),
    pair("사이즈", "핏"),
    pair("캐주얼", "정장"),
    pair("유행", "클래식"),
    pair("브랜드", "무신사"),
    pair("세일", "신상"),
    pair("코디", "단품"),
    pair("액세서리", "가방"),
    pair("지갑", "카드지갑"),
    pair("우산", "양산"),
    pair("모자", "장갑"),
    pair("목도리", "스카프"),
    pair("겨울코트", "패딩"),
    pair("봄자켓", "가디건"),
    pair("반팔", "긴팔"),
    pair("반바지", "긴바지"),
    pair("운동화", "구두"),
    pair("슬리퍼", "샌들"),
    pair("양말", "스타킹"),
    pair("속옷", "잠옷"),
    pair("세탁", "드라이"),
    pair("다림질", "걸기"),
    pair("옷장", "서랍"),
    pair("정리", "수납"),
    pair("이사", "청소"),
    pair("인테리어", "리모델링"),
    pair("월세", "관리비"),
    pair("전기", "가스"),
    pair("수도", "인터넷"),
    pair("와이파이", "데이터"),
    pair("공유기", "모뎀"),
    pair("에어컨", "난방"),
    pair("선풍기", "히터"),
    pair("가습기", "제습기"),
    pair("청소기", "로봇청소기"),
    pair("세탁기", "건조기"),
    pair("냉장고", "전자레인지"),
    pair("가스레인지", "인덕션"),
    pair("밥솥", "에어프라이어"),
    pair("커피머신", "믹서기"),
    pair("칼", "도마"),
    pair("냄비", "프라이팬"),
    pair("접시", "그릇"),
    pair("수저", "젓가락"),
    pair("컵", "텀블러"),
    pair("봉지", "용기"),
    pair("쓰레기", "재활용"),
    pair("분리수거", "음식물"),
    pair("벌레", "곰팡이"),
    pair("누수", "곰팡이"),
    pair("수리", "교체"),
    pair("AS", "보증"),
    pair("이웃", "관리실"),
    pair("경비", "택배"),
    pair("우편", "등기"),
    pair("택배", "퀵"),
    pair("배송조회", "수령"),
    pair("부재", "대리수령"),
    pair("반품", "교환"),
    pair("고객센터", "챗봇"),
    pair("문의", "불만"),
    pair("칭찬", "건의"),
    pair("리뷰", "후기"),
    pair("별점", "추천"),
    pair("인증", "후기"),
    pair("가짜", "정품"),
    pair("중고", "새제품"),
    pair("경매", "즉시구매"),
    pair("입찰", "낙찰"),
    pair("낙찰", "유찰"),
  ];
  for (const p of extraPairs) out.push([...p]);

  return out.filter(isLearnerQualityComparison);
}

function shuffleInPlace<T>(arr: T[]): void {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j]!, arr[i]!];
  }
}

function takeRandom(pool: string[][]): string[] | null {
  if (pool.length === 0) return null;
  const i = Math.floor(Math.random() * pool.length);
  return pool.splice(i, 1)[0] ?? null;
}

function parseTripleRate(argv: string[]): number {
  const flag = argv.find((a) => a.startsWith("--triple-rate="));
  if (flag) {
    const n = parseFloat(flag.slice("--triple-rate=".length));
    if (Number.isFinite(n)) return Math.min(1, Math.max(0, n));
  }
  return 0.5;
}

async function loadUsedKeys(): Promise<Set<string>> {
  const used = new Set<string>();

  const batchFiles = [
    "scripts/data/grammar-batch-100.txt",
    "scripts/data/grammar-batch-100-2.txt",
    "scripts/data/grammar-batch-100-3.txt",
    "scripts/data/grammar-batch-1000.txt",
    "scripts/data/grammar-batch-1000-random.txt",
  ];
  for (const rel of batchFiles) {
    for (const words of readBatchLines(path.join(ROOT, rel))) {
      used.add(slugKey(words));
    }
  }

  try {
    const { loadEnvLocal } = await import("./lib/env_local.mjs");
    loadEnvLocal(ROOT);
    const { getMongoDb } = await import("../src/lib/mongo.ts");
    const db = await getMongoDb();
    const docs = await db
      .collection("grammar_comparisons")
      .find({}, { projection: { slug: 1 } })
      .toArray();
    for (const doc of docs) {
      if (typeof doc.slug === "string") used.add(doc.slug);
    }
  } catch (err) {
    console.warn("Mongo skip:", err instanceof Error ? err.message : err);
  }

  return used;
}

function toLine(words: string[]): string {
  return words.join(",");
}

async function main() {
  const countArg = process.argv.find((a) => a.startsWith("--count="));
  const count = countArg
    ? Math.max(1, parseInt(countArg.slice("--count=".length), 10) || 1000)
    : 1000;
  const outIdx = process.argv.indexOf("--out");
  const outPath =
    outIdx >= 0 && process.argv[outIdx + 1]
      ? process.argv[outIdx + 1]!
      : "scripts/data/grammar-batch-1000.txt";
  const absOut = path.isAbsolute(outPath) ? outPath : path.join(ROOT, outPath);

  const used = await loadUsedKeys();
  const candidates = buildCandidates();
  const tripleRate = parseTripleRate(process.argv);

  const availTriples: string[][] = [];
  const availPairs: string[][] = [];

  for (const words of candidates) {
    const key = slugKey(words);
    if (used.has(key)) continue;
    if (words.length >= 3) availTriples.push(words);
    else availPairs.push(words);
  }

  shuffleInPlace(availTriples);
  shuffleInPlace(availPairs);

  const selected: string[][] = [];
  while (selected.length < count) {
    const wantTriple = Math.random() < tripleRate;
    const words =
      (wantTriple ? takeRandom(availTriples) : null) ??
      takeRandom(availPairs) ??
      takeRandom(availTriples);
    if (!words) break;
    selected.push(words);
  }

  if (selected.length < count) {
    console.error(
      `Only ${selected.length} unique topics available (need ${count}). pairs left=${availPairs.length} triples left=${availTriples.length}`,
    );
    process.exit(1);
  }

  shuffleInPlace(selected);
  const tripleCount = selected.filter((w) => w.length >= 3).length;

  const lines = [
    `# Grammar comparison batch — ${count} topics (dice ~${Math.round(tripleRate * 100)}% three-way, got ${tripleCount})`,
    ...selected.slice(0, count).map(toLine),
  ];

  fs.mkdirSync(path.dirname(absOut), { recursive: true });
  fs.writeFileSync(absOut, `${lines.join("\n")}\n`, "utf8");
  console.log(
    JSON.stringify(
      {
        out: absOut,
        total: count,
        triples: tripleCount,
        pairs: count - tripleCount,
        tripleRate,
        usedKeys: used.size,
      },
      null,
      2,
    ),
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
